# TCL File Generated by Component Editor 21.1
# Tue Nov 19 19:17:49 CET 2024
# DO NOT MODIFY


# 
# axi4_lite_booth "axi4_lite_booth" v1.0
#  2024.11.19.19:17:49
# 16-bit booth multiplier
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module axi4_lite_booth
# 
set_module_property DESCRIPTION "16-bit booth multiplier"
set_module_property NAME axi4_lite_booth
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME axi4_lite_booth
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi4_lite_booth
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi4_lite_booth.vhd VHDL PATH HDL_source/axi4_lite_booth/axi4_lite_booth.vhd TOP_LEVEL_FILE
add_fileset_file booth.sv SYSTEM_VERILOG PATH HDL_source/axi4_lite_booth/booth.sv


# 
# parameters
# 
add_parameter C_S_AXI_DATA_WIDTH INTEGER 32
set_parameter_property C_S_AXI_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property C_S_AXI_DATA_WIDTH DISPLAY_NAME C_S_AXI_DATA_WIDTH
set_parameter_property C_S_AXI_DATA_WIDTH TYPE INTEGER
set_parameter_property C_S_AXI_DATA_WIDTH UNITS None
set_parameter_property C_S_AXI_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S_AXI_DATA_WIDTH HDL_PARAMETER true
add_parameter C_S_AXI_ADDR_WIDTH INTEGER 4
set_parameter_property C_S_AXI_ADDR_WIDTH DEFAULT_VALUE 4
set_parameter_property C_S_AXI_ADDR_WIDTH DISPLAY_NAME C_S_AXI_ADDR_WIDTH
set_parameter_property C_S_AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property C_S_AXI_ADDR_WIDTH UNITS None
set_parameter_property C_S_AXI_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S_AXI_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint ""
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset reset
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq irq Output 1


# 
# connection point altera_axi4lite_slave
# 
add_interface altera_axi4lite_slave axi4lite end
set_interface_property altera_axi4lite_slave associatedClock clock
set_interface_property altera_axi4lite_slave associatedReset reset
set_interface_property altera_axi4lite_slave readAcceptanceCapability 1
set_interface_property altera_axi4lite_slave writeAcceptanceCapability 1
set_interface_property altera_axi4lite_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4lite_slave readDataReorderingDepth 1
set_interface_property altera_axi4lite_slave bridgesToMaster ""
set_interface_property altera_axi4lite_slave ENABLED true
set_interface_property altera_axi4lite_slave EXPORT_OF ""
set_interface_property altera_axi4lite_slave PORT_NAME_MAP ""
set_interface_property altera_axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4lite_slave axs_s0_AXI_AWADDR awaddr Input "((c_s_axi_addr_width-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave axs_s0_AXI_AWPROT awprot Input 3
add_interface_port altera_axi4lite_slave axs_s0_AXI_AWVALID awvalid Input 1
add_interface_port altera_axi4lite_slave axs_s0_AXI_AWREADY awready Output 1
add_interface_port altera_axi4lite_slave axs_s0_AXI_WDATA wdata Input "((c_s_axi_data_width-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave axs_s0_AXI_WSTRB wstrb Input "(((c_s_axi_data_width/8)-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave axs_s0_AXI_WVALID wvalid Input 1
add_interface_port altera_axi4lite_slave axs_s0_AXI_WREADY wready Output 1
add_interface_port altera_axi4lite_slave axs_s0_AXI_BRESP bresp Output 2
add_interface_port altera_axi4lite_slave axs_s0_AXI_BVALID bvalid Output 1
add_interface_port altera_axi4lite_slave axs_s0_AXI_BREADY bready Input 1
add_interface_port altera_axi4lite_slave axs_s0_AXI_ARADDR araddr Input "((c_s_axi_addr_width-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave axs_s0_AXI_ARPROT arprot Input 3
add_interface_port altera_axi4lite_slave axs_s0_AXI_ARVALID arvalid Input 1
add_interface_port altera_axi4lite_slave axs_s0_AXI_ARREADY arready Output 1
add_interface_port altera_axi4lite_slave axs_s0_AXI_RDATA rdata Output "((c_s_axi_data_width-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave axs_s0_AXI_RRESP rresp Output 2
add_interface_port altera_axi4lite_slave axs_s0_AXI_RVALID rvalid Output 1
add_interface_port altera_axi4lite_slave axs_s0_AXI_RREADY rready Input 1

