// lab1_system_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 21.1 842

`timescale 1 ps / 1 ps
module lab1_system_mm_interconnect_1 (
		input  wire [11:0] ARM_A9_HPS_h2f_lw_axi_master_awid,                                        //                                       ARM_A9_HPS_h2f_lw_axi_master.awid
		input  wire [20:0] ARM_A9_HPS_h2f_lw_axi_master_awaddr,                                      //                                                                   .awaddr
		input  wire [3:0]  ARM_A9_HPS_h2f_lw_axi_master_awlen,                                       //                                                                   .awlen
		input  wire [2:0]  ARM_A9_HPS_h2f_lw_axi_master_awsize,                                      //                                                                   .awsize
		input  wire [1:0]  ARM_A9_HPS_h2f_lw_axi_master_awburst,                                     //                                                                   .awburst
		input  wire [1:0]  ARM_A9_HPS_h2f_lw_axi_master_awlock,                                      //                                                                   .awlock
		input  wire [3:0]  ARM_A9_HPS_h2f_lw_axi_master_awcache,                                     //                                                                   .awcache
		input  wire [2:0]  ARM_A9_HPS_h2f_lw_axi_master_awprot,                                      //                                                                   .awprot
		input  wire        ARM_A9_HPS_h2f_lw_axi_master_awvalid,                                     //                                                                   .awvalid
		output wire        ARM_A9_HPS_h2f_lw_axi_master_awready,                                     //                                                                   .awready
		input  wire [11:0] ARM_A9_HPS_h2f_lw_axi_master_wid,                                         //                                                                   .wid
		input  wire [31:0] ARM_A9_HPS_h2f_lw_axi_master_wdata,                                       //                                                                   .wdata
		input  wire [3:0]  ARM_A9_HPS_h2f_lw_axi_master_wstrb,                                       //                                                                   .wstrb
		input  wire        ARM_A9_HPS_h2f_lw_axi_master_wlast,                                       //                                                                   .wlast
		input  wire        ARM_A9_HPS_h2f_lw_axi_master_wvalid,                                      //                                                                   .wvalid
		output wire        ARM_A9_HPS_h2f_lw_axi_master_wready,                                      //                                                                   .wready
		output wire [11:0] ARM_A9_HPS_h2f_lw_axi_master_bid,                                         //                                                                   .bid
		output wire [1:0]  ARM_A9_HPS_h2f_lw_axi_master_bresp,                                       //                                                                   .bresp
		output wire        ARM_A9_HPS_h2f_lw_axi_master_bvalid,                                      //                                                                   .bvalid
		input  wire        ARM_A9_HPS_h2f_lw_axi_master_bready,                                      //                                                                   .bready
		input  wire [11:0] ARM_A9_HPS_h2f_lw_axi_master_arid,                                        //                                                                   .arid
		input  wire [20:0] ARM_A9_HPS_h2f_lw_axi_master_araddr,                                      //                                                                   .araddr
		input  wire [3:0]  ARM_A9_HPS_h2f_lw_axi_master_arlen,                                       //                                                                   .arlen
		input  wire [2:0]  ARM_A9_HPS_h2f_lw_axi_master_arsize,                                      //                                                                   .arsize
		input  wire [1:0]  ARM_A9_HPS_h2f_lw_axi_master_arburst,                                     //                                                                   .arburst
		input  wire [1:0]  ARM_A9_HPS_h2f_lw_axi_master_arlock,                                      //                                                                   .arlock
		input  wire [3:0]  ARM_A9_HPS_h2f_lw_axi_master_arcache,                                     //                                                                   .arcache
		input  wire [2:0]  ARM_A9_HPS_h2f_lw_axi_master_arprot,                                      //                                                                   .arprot
		input  wire        ARM_A9_HPS_h2f_lw_axi_master_arvalid,                                     //                                                                   .arvalid
		output wire        ARM_A9_HPS_h2f_lw_axi_master_arready,                                     //                                                                   .arready
		output wire [11:0] ARM_A9_HPS_h2f_lw_axi_master_rid,                                         //                                                                   .rid
		output wire [31:0] ARM_A9_HPS_h2f_lw_axi_master_rdata,                                       //                                                                   .rdata
		output wire [1:0]  ARM_A9_HPS_h2f_lw_axi_master_rresp,                                       //                                                                   .rresp
		output wire        ARM_A9_HPS_h2f_lw_axi_master_rlast,                                       //                                                                   .rlast
		output wire        ARM_A9_HPS_h2f_lw_axi_master_rvalid,                                      //                                                                   .rvalid
		input  wire        ARM_A9_HPS_h2f_lw_axi_master_rready,                                      //                                                                   .rready
		output wire [3:0]  axi4_lite_booth_0_altera_axi4lite_slave_awaddr,                           //                            axi4_lite_booth_0_altera_axi4lite_slave.awaddr
		output wire [2:0]  axi4_lite_booth_0_altera_axi4lite_slave_awprot,                           //                                                                   .awprot
		output wire        axi4_lite_booth_0_altera_axi4lite_slave_awvalid,                          //                                                                   .awvalid
		input  wire        axi4_lite_booth_0_altera_axi4lite_slave_awready,                          //                                                                   .awready
		output wire [31:0] axi4_lite_booth_0_altera_axi4lite_slave_wdata,                            //                                                                   .wdata
		output wire [3:0]  axi4_lite_booth_0_altera_axi4lite_slave_wstrb,                            //                                                                   .wstrb
		output wire        axi4_lite_booth_0_altera_axi4lite_slave_wvalid,                           //                                                                   .wvalid
		input  wire        axi4_lite_booth_0_altera_axi4lite_slave_wready,                           //                                                                   .wready
		input  wire [1:0]  axi4_lite_booth_0_altera_axi4lite_slave_bresp,                            //                                                                   .bresp
		input  wire        axi4_lite_booth_0_altera_axi4lite_slave_bvalid,                           //                                                                   .bvalid
		output wire        axi4_lite_booth_0_altera_axi4lite_slave_bready,                           //                                                                   .bready
		output wire [3:0]  axi4_lite_booth_0_altera_axi4lite_slave_araddr,                           //                                                                   .araddr
		output wire [2:0]  axi4_lite_booth_0_altera_axi4lite_slave_arprot,                           //                                                                   .arprot
		output wire        axi4_lite_booth_0_altera_axi4lite_slave_arvalid,                          //                                                                   .arvalid
		input  wire        axi4_lite_booth_0_altera_axi4lite_slave_arready,                          //                                                                   .arready
		input  wire [31:0] axi4_lite_booth_0_altera_axi4lite_slave_rdata,                            //                                                                   .rdata
		input  wire [1:0]  axi4_lite_booth_0_altera_axi4lite_slave_rresp,                            //                                                                   .rresp
		input  wire        axi4_lite_booth_0_altera_axi4lite_slave_rvalid,                           //                                                                   .rvalid
		output wire        axi4_lite_booth_0_altera_axi4lite_slave_rready,                           //                                                                   .rready
		input  wire        System_PLL_sys_clk_clk,                                                   //                                                 System_PLL_sys_clk.clk
		input  wire        ARM_A9_HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset, // ARM_A9_HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset.reset
		input  wire        axi4_lite_booth_0_reset_reset_bridge_in_reset_reset                       //                      axi4_lite_booth_0_reset_reset_bridge_in_reset.reset
	);

	wire          rsp_mux_src_valid;                                                              // rsp_mux:src_valid -> ARM_A9_HPS_h2f_lw_axi_master_agent:write_rp_valid
	wire  [111:0] rsp_mux_src_data;                                                               // rsp_mux:src_data -> ARM_A9_HPS_h2f_lw_axi_master_agent:write_rp_data
	wire          rsp_mux_src_ready;                                                              // ARM_A9_HPS_h2f_lw_axi_master_agent:write_rp_ready -> rsp_mux:src_ready
	wire    [1:0] rsp_mux_src_channel;                                                            // rsp_mux:src_channel -> ARM_A9_HPS_h2f_lw_axi_master_agent:write_rp_channel
	wire          rsp_mux_src_startofpacket;                                                      // rsp_mux:src_startofpacket -> ARM_A9_HPS_h2f_lw_axi_master_agent:write_rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                                        // rsp_mux:src_endofpacket -> ARM_A9_HPS_h2f_lw_axi_master_agent:write_rp_endofpacket
	wire          rsp_mux_001_src_valid;                                                          // rsp_mux_001:src_valid -> ARM_A9_HPS_h2f_lw_axi_master_agent:read_rp_valid
	wire  [111:0] rsp_mux_001_src_data;                                                           // rsp_mux_001:src_data -> ARM_A9_HPS_h2f_lw_axi_master_agent:read_rp_data
	wire          rsp_mux_001_src_ready;                                                          // ARM_A9_HPS_h2f_lw_axi_master_agent:read_rp_ready -> rsp_mux_001:src_ready
	wire    [1:0] rsp_mux_001_src_channel;                                                        // rsp_mux_001:src_channel -> ARM_A9_HPS_h2f_lw_axi_master_agent:read_rp_channel
	wire          rsp_mux_001_src_startofpacket;                                                  // rsp_mux_001:src_startofpacket -> ARM_A9_HPS_h2f_lw_axi_master_agent:read_rp_startofpacket
	wire          rsp_mux_001_src_endofpacket;                                                    // rsp_mux_001:src_endofpacket -> ARM_A9_HPS_h2f_lw_axi_master_agent:read_rp_endofpacket
	wire          arm_a9_hps_h2f_lw_axi_master_agent_write_cp_valid;                              // ARM_A9_HPS_h2f_lw_axi_master_agent:write_cp_valid -> router:sink_valid
	wire  [111:0] arm_a9_hps_h2f_lw_axi_master_agent_write_cp_data;                               // ARM_A9_HPS_h2f_lw_axi_master_agent:write_cp_data -> router:sink_data
	wire          arm_a9_hps_h2f_lw_axi_master_agent_write_cp_ready;                              // router:sink_ready -> ARM_A9_HPS_h2f_lw_axi_master_agent:write_cp_ready
	wire          arm_a9_hps_h2f_lw_axi_master_agent_write_cp_startofpacket;                      // ARM_A9_HPS_h2f_lw_axi_master_agent:write_cp_startofpacket -> router:sink_startofpacket
	wire          arm_a9_hps_h2f_lw_axi_master_agent_write_cp_endofpacket;                        // ARM_A9_HPS_h2f_lw_axi_master_agent:write_cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                               // router:src_valid -> cmd_demux:sink_valid
	wire  [111:0] router_src_data;                                                                // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                               // cmd_demux:sink_ready -> router:src_ready
	wire    [1:0] router_src_channel;                                                             // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                                       // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                                         // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          arm_a9_hps_h2f_lw_axi_master_agent_read_cp_valid;                               // ARM_A9_HPS_h2f_lw_axi_master_agent:read_cp_valid -> router_001:sink_valid
	wire  [111:0] arm_a9_hps_h2f_lw_axi_master_agent_read_cp_data;                                // ARM_A9_HPS_h2f_lw_axi_master_agent:read_cp_data -> router_001:sink_data
	wire          arm_a9_hps_h2f_lw_axi_master_agent_read_cp_ready;                               // router_001:sink_ready -> ARM_A9_HPS_h2f_lw_axi_master_agent:read_cp_ready
	wire          arm_a9_hps_h2f_lw_axi_master_agent_read_cp_startofpacket;                       // ARM_A9_HPS_h2f_lw_axi_master_agent:read_cp_startofpacket -> router_001:sink_startofpacket
	wire          arm_a9_hps_h2f_lw_axi_master_agent_read_cp_endofpacket;                         // ARM_A9_HPS_h2f_lw_axi_master_agent:read_cp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                                           // router_001:src_valid -> cmd_demux_001:sink_valid
	wire  [111:0] router_001_src_data;                                                            // router_001:src_data -> cmd_demux_001:sink_data
	wire          router_001_src_ready;                                                           // cmd_demux_001:sink_ready -> router_001:src_ready
	wire    [1:0] router_001_src_channel;                                                         // router_001:src_channel -> cmd_demux_001:sink_channel
	wire          router_001_src_startofpacket;                                                   // router_001:src_startofpacket -> cmd_demux_001:sink_startofpacket
	wire          router_001_src_endofpacket;                                                     // router_001:src_endofpacket -> cmd_demux_001:sink_endofpacket
	wire          axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_valid;                   // axi4_lite_booth_0_altera_axi4lite_slave_agent:write_rp_valid -> router_002:sink_valid
	wire  [111:0] axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_data;                    // axi4_lite_booth_0_altera_axi4lite_slave_agent:write_rp_data -> router_002:sink_data
	wire          axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_ready;                   // router_002:sink_ready -> axi4_lite_booth_0_altera_axi4lite_slave_agent:write_rp_ready
	wire          axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_startofpacket;           // axi4_lite_booth_0_altera_axi4lite_slave_agent:write_rp_startofpacket -> router_002:sink_startofpacket
	wire          axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_endofpacket;             // axi4_lite_booth_0_altera_axi4lite_slave_agent:write_rp_endofpacket -> router_002:sink_endofpacket
	wire          router_002_src_valid;                                                           // router_002:src_valid -> rsp_demux:sink_valid
	wire  [111:0] router_002_src_data;                                                            // router_002:src_data -> rsp_demux:sink_data
	wire          router_002_src_ready;                                                           // rsp_demux:sink_ready -> router_002:src_ready
	wire    [1:0] router_002_src_channel;                                                         // router_002:src_channel -> rsp_demux:sink_channel
	wire          router_002_src_startofpacket;                                                   // router_002:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_002_src_endofpacket;                                                     // router_002:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_valid;                    // axi4_lite_booth_0_altera_axi4lite_slave_agent:read_rp_valid -> router_003:sink_valid
	wire  [111:0] axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_data;                     // axi4_lite_booth_0_altera_axi4lite_slave_agent:read_rp_data -> router_003:sink_data
	wire          axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_ready;                    // router_003:sink_ready -> axi4_lite_booth_0_altera_axi4lite_slave_agent:read_rp_ready
	wire          axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_startofpacket;            // axi4_lite_booth_0_altera_axi4lite_slave_agent:read_rp_startofpacket -> router_003:sink_startofpacket
	wire          axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_endofpacket;              // axi4_lite_booth_0_altera_axi4lite_slave_agent:read_rp_endofpacket -> router_003:sink_endofpacket
	wire          router_003_src_valid;                                                           // router_003:src_valid -> rsp_demux_001:sink_valid
	wire  [111:0] router_003_src_data;                                                            // router_003:src_data -> rsp_demux_001:sink_data
	wire          router_003_src_ready;                                                           // rsp_demux_001:sink_ready -> router_003:src_ready
	wire    [1:0] router_003_src_channel;                                                         // router_003:src_channel -> rsp_demux_001:sink_channel
	wire          router_003_src_startofpacket;                                                   // router_003:src_startofpacket -> rsp_demux_001:sink_startofpacket
	wire          router_003_src_endofpacket;                                                     // router_003:src_endofpacket -> rsp_demux_001:sink_endofpacket
	wire          cmd_mux_src_valid;                                                              // cmd_mux:src_valid -> axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter:sink0_valid
	wire  [111:0] cmd_mux_src_data;                                                               // cmd_mux:src_data -> axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter:sink0_data
	wire          cmd_mux_src_ready;                                                              // axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter:sink0_ready -> cmd_mux:src_ready
	wire    [1:0] cmd_mux_src_channel;                                                            // cmd_mux:src_channel -> axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter:sink0_channel
	wire          cmd_mux_src_startofpacket;                                                      // cmd_mux:src_startofpacket -> axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter:sink0_startofpacket
	wire          cmd_mux_src_endofpacket;                                                        // cmd_mux:src_endofpacket -> axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter:sink0_endofpacket
	wire          axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_valid;         // axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter:source0_valid -> axi4_lite_booth_0_altera_axi4lite_slave_agent:write_cp_valid
	wire  [111:0] axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_data;          // axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter:source0_data -> axi4_lite_booth_0_altera_axi4lite_slave_agent:write_cp_data
	wire          axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_ready;         // axi4_lite_booth_0_altera_axi4lite_slave_agent:write_cp_ready -> axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter:source0_ready
	wire    [1:0] axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_channel;       // axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter:source0_channel -> axi4_lite_booth_0_altera_axi4lite_slave_agent:write_cp_channel
	wire          axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_startofpacket; // axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter:source0_startofpacket -> axi4_lite_booth_0_altera_axi4lite_slave_agent:write_cp_startofpacket
	wire          axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_endofpacket;   // axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter:source0_endofpacket -> axi4_lite_booth_0_altera_axi4lite_slave_agent:write_cp_endofpacket
	wire          cmd_mux_001_src_valid;                                                          // cmd_mux_001:src_valid -> axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter:sink0_valid
	wire  [111:0] cmd_mux_001_src_data;                                                           // cmd_mux_001:src_data -> axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter:sink0_data
	wire          cmd_mux_001_src_ready;                                                          // axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter:sink0_ready -> cmd_mux_001:src_ready
	wire    [1:0] cmd_mux_001_src_channel;                                                        // cmd_mux_001:src_channel -> axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter:sink0_channel
	wire          cmd_mux_001_src_startofpacket;                                                  // cmd_mux_001:src_startofpacket -> axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter:sink0_startofpacket
	wire          cmd_mux_001_src_endofpacket;                                                    // cmd_mux_001:src_endofpacket -> axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter:sink0_endofpacket
	wire          axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_valid;         // axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter:source0_valid -> axi4_lite_booth_0_altera_axi4lite_slave_agent:read_cp_valid
	wire  [111:0] axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_data;          // axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter:source0_data -> axi4_lite_booth_0_altera_axi4lite_slave_agent:read_cp_data
	wire          axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_ready;         // axi4_lite_booth_0_altera_axi4lite_slave_agent:read_cp_ready -> axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter:source0_ready
	wire    [1:0] axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_channel;       // axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter:source0_channel -> axi4_lite_booth_0_altera_axi4lite_slave_agent:read_cp_channel
	wire          axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_startofpacket; // axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter:source0_startofpacket -> axi4_lite_booth_0_altera_axi4lite_slave_agent:read_cp_startofpacket
	wire          axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_endofpacket;   // axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter:source0_endofpacket -> axi4_lite_booth_0_altera_axi4lite_slave_agent:read_cp_endofpacket
	wire          cmd_demux_src0_valid;                                                           // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [111:0] cmd_demux_src0_data;                                                            // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                                           // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [1:0] cmd_demux_src0_channel;                                                         // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                                   // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                                     // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          cmd_demux_001_src0_valid;                                                       // cmd_demux_001:src0_valid -> cmd_mux_001:sink0_valid
	wire  [111:0] cmd_demux_001_src0_data;                                                        // cmd_demux_001:src0_data -> cmd_mux_001:sink0_data
	wire          cmd_demux_001_src0_ready;                                                       // cmd_mux_001:sink0_ready -> cmd_demux_001:src0_ready
	wire    [1:0] cmd_demux_001_src0_channel;                                                     // cmd_demux_001:src0_channel -> cmd_mux_001:sink0_channel
	wire          cmd_demux_001_src0_startofpacket;                                               // cmd_demux_001:src0_startofpacket -> cmd_mux_001:sink0_startofpacket
	wire          cmd_demux_001_src0_endofpacket;                                                 // cmd_demux_001:src0_endofpacket -> cmd_mux_001:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                                           // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [111:0] rsp_demux_src0_data;                                                            // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                                           // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [1:0] rsp_demux_src0_channel;                                                         // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                                   // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                                     // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          rsp_demux_001_src0_valid;                                                       // rsp_demux_001:src0_valid -> rsp_mux_001:sink0_valid
	wire  [111:0] rsp_demux_001_src0_data;                                                        // rsp_demux_001:src0_data -> rsp_mux_001:sink0_data
	wire          rsp_demux_001_src0_ready;                                                       // rsp_mux_001:sink0_ready -> rsp_demux_001:src0_ready
	wire    [1:0] rsp_demux_001_src0_channel;                                                     // rsp_demux_001:src0_channel -> rsp_mux_001:sink0_channel
	wire          rsp_demux_001_src0_startofpacket;                                               // rsp_demux_001:src0_startofpacket -> rsp_mux_001:sink0_startofpacket
	wire          rsp_demux_001_src0_endofpacket;                                                 // rsp_demux_001:src0_endofpacket -> rsp_mux_001:sink0_endofpacket

	altera_merlin_axi_master_ni #(
		.ID_WIDTH                  (12),
		.ADDR_WIDTH                (21),
		.RDATA_WIDTH               (32),
		.WDATA_WIDTH               (32),
		.ADDR_USER_WIDTH           (1),
		.DATA_USER_WIDTH           (1),
		.AXI_BURST_LENGTH_WIDTH    (4),
		.AXI_LOCK_WIDTH            (2),
		.AXI_VERSION               ("AXI3"),
		.WRITE_ISSUING_CAPABILITY  (8),
		.READ_ISSUING_CAPABILITY   (8),
		.PKT_BEGIN_BURST           (84),
		.PKT_CACHE_H               (106),
		.PKT_CACHE_L               (103),
		.PKT_ADDR_SIDEBAND_H       (82),
		.PKT_ADDR_SIDEBAND_L       (82),
		.PKT_PROTECTION_H          (102),
		.PKT_PROTECTION_L          (100),
		.PKT_BURST_SIZE_H          (79),
		.PKT_BURST_SIZE_L          (77),
		.PKT_BURST_TYPE_H          (81),
		.PKT_BURST_TYPE_L          (80),
		.PKT_RESPONSE_STATUS_L     (107),
		.PKT_RESPONSE_STATUS_H     (108),
		.PKT_BURSTWRAP_H           (76),
		.PKT_BURSTWRAP_L           (70),
		.PKT_BYTE_CNT_H            (69),
		.PKT_BYTE_CNT_L            (63),
		.PKT_ADDR_H                (56),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_EXCLUSIVE       (62),
		.PKT_TRANS_LOCK            (61),
		.PKT_TRANS_COMPRESSED_READ (57),
		.PKT_TRANS_POSTED          (58),
		.PKT_TRANS_WRITE           (59),
		.PKT_TRANS_READ            (60),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (86),
		.PKT_SRC_ID_L              (86),
		.PKT_DEST_ID_H             (87),
		.PKT_DEST_ID_L             (87),
		.PKT_THREAD_ID_H           (99),
		.PKT_THREAD_ID_L           (88),
		.PKT_QOS_L                 (85),
		.PKT_QOS_H                 (85),
		.PKT_ORI_BURST_SIZE_L      (109),
		.PKT_ORI_BURST_SIZE_H      (111),
		.PKT_DATA_SIDEBAND_H       (83),
		.PKT_DATA_SIDEBAND_L       (83),
		.ST_DATA_W                 (112),
		.ST_CHANNEL_W              (2),
		.ID                        (0)
	) arm_a9_hps_h2f_lw_axi_master_agent (
		.aclk                   (System_PLL_sys_clk_clk),                                                    //              clk.clk
		.aresetn                (~ARM_A9_HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), //        clk_reset.reset_n
		.write_cp_valid         (arm_a9_hps_h2f_lw_axi_master_agent_write_cp_valid),                         //         write_cp.valid
		.write_cp_data          (arm_a9_hps_h2f_lw_axi_master_agent_write_cp_data),                          //                 .data
		.write_cp_startofpacket (arm_a9_hps_h2f_lw_axi_master_agent_write_cp_startofpacket),                 //                 .startofpacket
		.write_cp_endofpacket   (arm_a9_hps_h2f_lw_axi_master_agent_write_cp_endofpacket),                   //                 .endofpacket
		.write_cp_ready         (arm_a9_hps_h2f_lw_axi_master_agent_write_cp_ready),                         //                 .ready
		.write_rp_valid         (rsp_mux_src_valid),                                                         //         write_rp.valid
		.write_rp_data          (rsp_mux_src_data),                                                          //                 .data
		.write_rp_channel       (rsp_mux_src_channel),                                                       //                 .channel
		.write_rp_startofpacket (rsp_mux_src_startofpacket),                                                 //                 .startofpacket
		.write_rp_endofpacket   (rsp_mux_src_endofpacket),                                                   //                 .endofpacket
		.write_rp_ready         (rsp_mux_src_ready),                                                         //                 .ready
		.read_cp_valid          (arm_a9_hps_h2f_lw_axi_master_agent_read_cp_valid),                          //          read_cp.valid
		.read_cp_data           (arm_a9_hps_h2f_lw_axi_master_agent_read_cp_data),                           //                 .data
		.read_cp_startofpacket  (arm_a9_hps_h2f_lw_axi_master_agent_read_cp_startofpacket),                  //                 .startofpacket
		.read_cp_endofpacket    (arm_a9_hps_h2f_lw_axi_master_agent_read_cp_endofpacket),                    //                 .endofpacket
		.read_cp_ready          (arm_a9_hps_h2f_lw_axi_master_agent_read_cp_ready),                          //                 .ready
		.read_rp_valid          (rsp_mux_001_src_valid),                                                     //          read_rp.valid
		.read_rp_data           (rsp_mux_001_src_data),                                                      //                 .data
		.read_rp_channel        (rsp_mux_001_src_channel),                                                   //                 .channel
		.read_rp_startofpacket  (rsp_mux_001_src_startofpacket),                                             //                 .startofpacket
		.read_rp_endofpacket    (rsp_mux_001_src_endofpacket),                                               //                 .endofpacket
		.read_rp_ready          (rsp_mux_001_src_ready),                                                     //                 .ready
		.awid                   (ARM_A9_HPS_h2f_lw_axi_master_awid),                                         // altera_axi_slave.awid
		.awaddr                 (ARM_A9_HPS_h2f_lw_axi_master_awaddr),                                       //                 .awaddr
		.awlen                  (ARM_A9_HPS_h2f_lw_axi_master_awlen),                                        //                 .awlen
		.awsize                 (ARM_A9_HPS_h2f_lw_axi_master_awsize),                                       //                 .awsize
		.awburst                (ARM_A9_HPS_h2f_lw_axi_master_awburst),                                      //                 .awburst
		.awlock                 (ARM_A9_HPS_h2f_lw_axi_master_awlock),                                       //                 .awlock
		.awcache                (ARM_A9_HPS_h2f_lw_axi_master_awcache),                                      //                 .awcache
		.awprot                 (ARM_A9_HPS_h2f_lw_axi_master_awprot),                                       //                 .awprot
		.awvalid                (ARM_A9_HPS_h2f_lw_axi_master_awvalid),                                      //                 .awvalid
		.awready                (ARM_A9_HPS_h2f_lw_axi_master_awready),                                      //                 .awready
		.wid                    (ARM_A9_HPS_h2f_lw_axi_master_wid),                                          //                 .wid
		.wdata                  (ARM_A9_HPS_h2f_lw_axi_master_wdata),                                        //                 .wdata
		.wstrb                  (ARM_A9_HPS_h2f_lw_axi_master_wstrb),                                        //                 .wstrb
		.wlast                  (ARM_A9_HPS_h2f_lw_axi_master_wlast),                                        //                 .wlast
		.wvalid                 (ARM_A9_HPS_h2f_lw_axi_master_wvalid),                                       //                 .wvalid
		.wready                 (ARM_A9_HPS_h2f_lw_axi_master_wready),                                       //                 .wready
		.bid                    (ARM_A9_HPS_h2f_lw_axi_master_bid),                                          //                 .bid
		.bresp                  (ARM_A9_HPS_h2f_lw_axi_master_bresp),                                        //                 .bresp
		.bvalid                 (ARM_A9_HPS_h2f_lw_axi_master_bvalid),                                       //                 .bvalid
		.bready                 (ARM_A9_HPS_h2f_lw_axi_master_bready),                                       //                 .bready
		.arid                   (ARM_A9_HPS_h2f_lw_axi_master_arid),                                         //                 .arid
		.araddr                 (ARM_A9_HPS_h2f_lw_axi_master_araddr),                                       //                 .araddr
		.arlen                  (ARM_A9_HPS_h2f_lw_axi_master_arlen),                                        //                 .arlen
		.arsize                 (ARM_A9_HPS_h2f_lw_axi_master_arsize),                                       //                 .arsize
		.arburst                (ARM_A9_HPS_h2f_lw_axi_master_arburst),                                      //                 .arburst
		.arlock                 (ARM_A9_HPS_h2f_lw_axi_master_arlock),                                       //                 .arlock
		.arcache                (ARM_A9_HPS_h2f_lw_axi_master_arcache),                                      //                 .arcache
		.arprot                 (ARM_A9_HPS_h2f_lw_axi_master_arprot),                                       //                 .arprot
		.arvalid                (ARM_A9_HPS_h2f_lw_axi_master_arvalid),                                      //                 .arvalid
		.arready                (ARM_A9_HPS_h2f_lw_axi_master_arready),                                      //                 .arready
		.rid                    (ARM_A9_HPS_h2f_lw_axi_master_rid),                                          //                 .rid
		.rdata                  (ARM_A9_HPS_h2f_lw_axi_master_rdata),                                        //                 .rdata
		.rresp                  (ARM_A9_HPS_h2f_lw_axi_master_rresp),                                        //                 .rresp
		.rlast                  (ARM_A9_HPS_h2f_lw_axi_master_rlast),                                        //                 .rlast
		.rvalid                 (ARM_A9_HPS_h2f_lw_axi_master_rvalid),                                       //                 .rvalid
		.rready                 (ARM_A9_HPS_h2f_lw_axi_master_rready),                                       //                 .rready
		.awuser                 (1'b0),                                                                      //      (terminated)
		.aruser                 (1'b0),                                                                      //      (terminated)
		.awqos                  (4'b0000),                                                                   //      (terminated)
		.arqos                  (4'b0000),                                                                   //      (terminated)
		.awregion               (4'b0000),                                                                   //      (terminated)
		.arregion               (4'b0000),                                                                   //      (terminated)
		.wuser                  (1'b0),                                                                      //      (terminated)
		.ruser                  (),                                                                          //      (terminated)
		.buser                  ()                                                                           //      (terminated)
	);

	altera_merlin_axi_slave_ni #(
		.PKT_QOS_H                   (85),
		.PKT_QOS_L                   (85),
		.PKT_THREAD_ID_H             (99),
		.PKT_THREAD_ID_L             (88),
		.PKT_RESPONSE_STATUS_H       (108),
		.PKT_RESPONSE_STATUS_L       (107),
		.PKT_BEGIN_BURST             (84),
		.PKT_CACHE_H                 (106),
		.PKT_CACHE_L                 (103),
		.PKT_DATA_SIDEBAND_H         (83),
		.PKT_DATA_SIDEBAND_L         (83),
		.PKT_ADDR_SIDEBAND_H         (82),
		.PKT_ADDR_SIDEBAND_L         (82),
		.PKT_BURST_TYPE_H            (81),
		.PKT_BURST_TYPE_L            (80),
		.PKT_PROTECTION_H            (102),
		.PKT_PROTECTION_L            (100),
		.PKT_BURST_SIZE_H            (79),
		.PKT_BURST_SIZE_L            (77),
		.PKT_BURSTWRAP_H             (76),
		.PKT_BURSTWRAP_L             (70),
		.PKT_BYTE_CNT_H              (69),
		.PKT_BYTE_CNT_L              (63),
		.PKT_ADDR_H                  (56),
		.PKT_ADDR_L                  (36),
		.PKT_TRANS_EXCLUSIVE         (62),
		.PKT_TRANS_LOCK              (61),
		.PKT_TRANS_COMPRESSED_READ   (57),
		.PKT_TRANS_POSTED            (58),
		.PKT_TRANS_WRITE             (59),
		.PKT_TRANS_READ              (60),
		.PKT_DATA_H                  (31),
		.PKT_DATA_L                  (0),
		.PKT_BYTEEN_H                (35),
		.PKT_BYTEEN_L                (32),
		.PKT_SRC_ID_H                (86),
		.PKT_SRC_ID_L                (86),
		.PKT_DEST_ID_H               (87),
		.PKT_DEST_ID_L               (87),
		.PKT_ORI_BURST_SIZE_L        (109),
		.PKT_ORI_BURST_SIZE_H        (111),
		.ADDR_USER_WIDTH             (1),
		.DATA_USER_WIDTH             (1),
		.ST_DATA_W                   (112),
		.ADDR_WIDTH                  (4),
		.RDATA_WIDTH                 (32),
		.WDATA_WIDTH                 (32),
		.ST_CHANNEL_W                (2),
		.AXI_SLAVE_ID_W              (1),
		.PASS_ID_TO_SLAVE            (0),
		.AXI_VERSION                 ("AXI4Lite"),
		.WRITE_ACCEPTANCE_CAPABILITY (1),
		.READ_ACCEPTANCE_CAPABILITY  (1)
	) axi4_lite_booth_0_altera_axi4lite_slave_agent (
		.aclk                   (System_PLL_sys_clk_clk),                                                         //        clock_sink.clk
		.aresetn                (~axi4_lite_booth_0_reset_reset_bridge_in_reset_reset),                           //        reset_sink.reset_n
		.read_cp_valid          (axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_valid),         //           read_cp.valid
		.read_cp_ready          (axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_ready),         //                  .ready
		.read_cp_data           (axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_data),          //                  .data
		.read_cp_channel        (axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_channel),       //                  .channel
		.read_cp_startofpacket  (axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_startofpacket), //                  .startofpacket
		.read_cp_endofpacket    (axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_endofpacket),   //                  .endofpacket
		.write_cp_ready         (axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_ready),         //          write_cp.ready
		.write_cp_valid         (axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_valid),         //                  .valid
		.write_cp_data          (axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_data),          //                  .data
		.write_cp_channel       (axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_channel),       //                  .channel
		.write_cp_startofpacket (axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_startofpacket), //                  .startofpacket
		.write_cp_endofpacket   (axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_endofpacket),   //                  .endofpacket
		.read_rp_ready          (axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_ready),                    //           read_rp.ready
		.read_rp_valid          (axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_valid),                    //                  .valid
		.read_rp_data           (axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_data),                     //                  .data
		.read_rp_startofpacket  (axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_startofpacket),            //                  .startofpacket
		.read_rp_endofpacket    (axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_endofpacket),              //                  .endofpacket
		.write_rp_ready         (axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_ready),                   //          write_rp.ready
		.write_rp_valid         (axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_valid),                   //                  .valid
		.write_rp_data          (axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_data),                    //                  .data
		.write_rp_startofpacket (axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_startofpacket),           //                  .startofpacket
		.write_rp_endofpacket   (axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_endofpacket),             //                  .endofpacket
		.awaddr                 (axi4_lite_booth_0_altera_axi4lite_slave_awaddr),                                 // altera_axi_master.awaddr
		.awprot                 (axi4_lite_booth_0_altera_axi4lite_slave_awprot),                                 //                  .awprot
		.awvalid                (axi4_lite_booth_0_altera_axi4lite_slave_awvalid),                                //                  .awvalid
		.awready                (axi4_lite_booth_0_altera_axi4lite_slave_awready),                                //                  .awready
		.wdata                  (axi4_lite_booth_0_altera_axi4lite_slave_wdata),                                  //                  .wdata
		.wstrb                  (axi4_lite_booth_0_altera_axi4lite_slave_wstrb),                                  //                  .wstrb
		.wvalid                 (axi4_lite_booth_0_altera_axi4lite_slave_wvalid),                                 //                  .wvalid
		.wready                 (axi4_lite_booth_0_altera_axi4lite_slave_wready),                                 //                  .wready
		.bresp                  (axi4_lite_booth_0_altera_axi4lite_slave_bresp),                                  //                  .bresp
		.bvalid                 (axi4_lite_booth_0_altera_axi4lite_slave_bvalid),                                 //                  .bvalid
		.bready                 (axi4_lite_booth_0_altera_axi4lite_slave_bready),                                 //                  .bready
		.araddr                 (axi4_lite_booth_0_altera_axi4lite_slave_araddr),                                 //                  .araddr
		.arprot                 (axi4_lite_booth_0_altera_axi4lite_slave_arprot),                                 //                  .arprot
		.arvalid                (axi4_lite_booth_0_altera_axi4lite_slave_arvalid),                                //                  .arvalid
		.arready                (axi4_lite_booth_0_altera_axi4lite_slave_arready),                                //                  .arready
		.rdata                  (axi4_lite_booth_0_altera_axi4lite_slave_rdata),                                  //                  .rdata
		.rresp                  (axi4_lite_booth_0_altera_axi4lite_slave_rresp),                                  //                  .rresp
		.rvalid                 (axi4_lite_booth_0_altera_axi4lite_slave_rvalid),                                 //                  .rvalid
		.rready                 (axi4_lite_booth_0_altera_axi4lite_slave_rready)                                  //                  .rready
	);

	lab1_system_mm_interconnect_1_router router (
		.sink_ready         (arm_a9_hps_h2f_lw_axi_master_agent_write_cp_ready),                        //      sink.ready
		.sink_valid         (arm_a9_hps_h2f_lw_axi_master_agent_write_cp_valid),                        //          .valid
		.sink_data          (arm_a9_hps_h2f_lw_axi_master_agent_write_cp_data),                         //          .data
		.sink_startofpacket (arm_a9_hps_h2f_lw_axi_master_agent_write_cp_startofpacket),                //          .startofpacket
		.sink_endofpacket   (arm_a9_hps_h2f_lw_axi_master_agent_write_cp_endofpacket),                  //          .endofpacket
		.clk                (System_PLL_sys_clk_clk),                                                   //       clk.clk
		.reset              (ARM_A9_HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                                                         //       src.ready
		.src_valid          (router_src_valid),                                                         //          .valid
		.src_data           (router_src_data),                                                          //          .data
		.src_channel        (router_src_channel),                                                       //          .channel
		.src_startofpacket  (router_src_startofpacket),                                                 //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                                    //          .endofpacket
	);

	lab1_system_mm_interconnect_1_router_001 router_001 (
		.sink_ready         (arm_a9_hps_h2f_lw_axi_master_agent_read_cp_ready),                         //      sink.ready
		.sink_valid         (arm_a9_hps_h2f_lw_axi_master_agent_read_cp_valid),                         //          .valid
		.sink_data          (arm_a9_hps_h2f_lw_axi_master_agent_read_cp_data),                          //          .data
		.sink_startofpacket (arm_a9_hps_h2f_lw_axi_master_agent_read_cp_startofpacket),                 //          .startofpacket
		.sink_endofpacket   (arm_a9_hps_h2f_lw_axi_master_agent_read_cp_endofpacket),                   //          .endofpacket
		.clk                (System_PLL_sys_clk_clk),                                                   //       clk.clk
		.reset              (ARM_A9_HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                                                     //       src.ready
		.src_valid          (router_001_src_valid),                                                     //          .valid
		.src_data           (router_001_src_data),                                                      //          .data
		.src_channel        (router_001_src_channel),                                                   //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                                             //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                                                //          .endofpacket
	);

	lab1_system_mm_interconnect_1_router_002 router_002 (
		.sink_ready         (axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_ready),         //      sink.ready
		.sink_valid         (axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_valid),         //          .valid
		.sink_data          (axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_data),          //          .data
		.sink_startofpacket (axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_startofpacket), //          .startofpacket
		.sink_endofpacket   (axi4_lite_booth_0_altera_axi4lite_slave_agent_write_rp_endofpacket),   //          .endofpacket
		.clk                (System_PLL_sys_clk_clk),                                               //       clk.clk
		.reset              (axi4_lite_booth_0_reset_reset_bridge_in_reset_reset),                  // clk_reset.reset
		.src_ready          (router_002_src_ready),                                                 //       src.ready
		.src_valid          (router_002_src_valid),                                                 //          .valid
		.src_data           (router_002_src_data),                                                  //          .data
		.src_channel        (router_002_src_channel),                                               //          .channel
		.src_startofpacket  (router_002_src_startofpacket),                                         //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                                            //          .endofpacket
	);

	lab1_system_mm_interconnect_1_router_003 router_003 (
		.sink_ready         (axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_ready),         //      sink.ready
		.sink_valid         (axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_valid),         //          .valid
		.sink_data          (axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_data),          //          .data
		.sink_startofpacket (axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_startofpacket), //          .startofpacket
		.sink_endofpacket   (axi4_lite_booth_0_altera_axi4lite_slave_agent_read_rp_endofpacket),   //          .endofpacket
		.clk                (System_PLL_sys_clk_clk),                                              //       clk.clk
		.reset              (axi4_lite_booth_0_reset_reset_bridge_in_reset_reset),                 // clk_reset.reset
		.src_ready          (router_003_src_ready),                                                //       src.ready
		.src_valid          (router_003_src_valid),                                                //          .valid
		.src_data           (router_003_src_data),                                                 //          .data
		.src_channel        (router_003_src_channel),                                              //          .channel
		.src_startofpacket  (router_003_src_startofpacket),                                        //          .startofpacket
		.src_endofpacket    (router_003_src_endofpacket)                                           //          .endofpacket
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (56),
		.PKT_ADDR_L                (36),
		.PKT_BEGIN_BURST           (84),
		.PKT_BYTE_CNT_H            (69),
		.PKT_BYTE_CNT_L            (63),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_BURST_SIZE_H          (79),
		.PKT_BURST_SIZE_L          (77),
		.PKT_BURST_TYPE_H          (81),
		.PKT_BURST_TYPE_L          (80),
		.PKT_BURSTWRAP_H           (76),
		.PKT_BURSTWRAP_L           (70),
		.PKT_TRANS_COMPRESSED_READ (57),
		.PKT_TRANS_WRITE           (59),
		.PKT_TRANS_READ            (60),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (1),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (112),
		.ST_CHANNEL_W              (2),
		.OUT_BYTE_CNT_H            (65),
		.OUT_BURSTWRAP_H           (76),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (0),
		.BURSTWRAP_CONST_VALUE     (0),
		.ADAPTER_VERSION           ("13.1")
	) axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter (
		.clk                   (System_PLL_sys_clk_clk),                                                         //       cr0.clk
		.reset                 (axi4_lite_booth_0_reset_reset_bridge_in_reset_reset),                            // cr0_reset.reset
		.sink0_valid           (cmd_mux_src_valid),                                                              //     sink0.valid
		.sink0_data            (cmd_mux_src_data),                                                               //          .data
		.sink0_channel         (cmd_mux_src_channel),                                                            //          .channel
		.sink0_startofpacket   (cmd_mux_src_startofpacket),                                                      //          .startofpacket
		.sink0_endofpacket     (cmd_mux_src_endofpacket),                                                        //          .endofpacket
		.sink0_ready           (cmd_mux_src_ready),                                                              //          .ready
		.source0_valid         (axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_valid),         //   source0.valid
		.source0_data          (axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_data),          //          .data
		.source0_channel       (axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_channel),       //          .channel
		.source0_startofpacket (axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_startofpacket), //          .startofpacket
		.source0_endofpacket   (axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_endofpacket),   //          .endofpacket
		.source0_ready         (axi4_lite_booth_0_altera_axi4lite_slave_wr_burst_adapter_source0_ready)          //          .ready
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (56),
		.PKT_ADDR_L                (36),
		.PKT_BEGIN_BURST           (84),
		.PKT_BYTE_CNT_H            (69),
		.PKT_BYTE_CNT_L            (63),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_BURST_SIZE_H          (79),
		.PKT_BURST_SIZE_L          (77),
		.PKT_BURST_TYPE_H          (81),
		.PKT_BURST_TYPE_L          (80),
		.PKT_BURSTWRAP_H           (76),
		.PKT_BURSTWRAP_L           (70),
		.PKT_TRANS_COMPRESSED_READ (57),
		.PKT_TRANS_WRITE           (59),
		.PKT_TRANS_READ            (60),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (1),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (112),
		.ST_CHANNEL_W              (2),
		.OUT_BYTE_CNT_H            (65),
		.OUT_BURSTWRAP_H           (76),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (0),
		.BURSTWRAP_CONST_VALUE     (0),
		.ADAPTER_VERSION           ("13.1")
	) axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter (
		.clk                   (System_PLL_sys_clk_clk),                                                         //       cr0.clk
		.reset                 (axi4_lite_booth_0_reset_reset_bridge_in_reset_reset),                            // cr0_reset.reset
		.sink0_valid           (cmd_mux_001_src_valid),                                                          //     sink0.valid
		.sink0_data            (cmd_mux_001_src_data),                                                           //          .data
		.sink0_channel         (cmd_mux_001_src_channel),                                                        //          .channel
		.sink0_startofpacket   (cmd_mux_001_src_startofpacket),                                                  //          .startofpacket
		.sink0_endofpacket     (cmd_mux_001_src_endofpacket),                                                    //          .endofpacket
		.sink0_ready           (cmd_mux_001_src_ready),                                                          //          .ready
		.source0_valid         (axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_valid),         //   source0.valid
		.source0_data          (axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_data),          //          .data
		.source0_channel       (axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_channel),       //          .channel
		.source0_startofpacket (axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_startofpacket), //          .startofpacket
		.source0_endofpacket   (axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_endofpacket),   //          .endofpacket
		.source0_ready         (axi4_lite_booth_0_altera_axi4lite_slave_rd_burst_adapter_source0_ready)          //          .ready
	);

	lab1_system_mm_interconnect_1_cmd_demux cmd_demux (
		.clk                (System_PLL_sys_clk_clk),                                                   //       clk.clk
		.reset              (ARM_A9_HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                                                         //      sink.ready
		.sink_channel       (router_src_channel),                                                       //          .channel
		.sink_data          (router_src_data),                                                          //          .data
		.sink_startofpacket (router_src_startofpacket),                                                 //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                                   //          .endofpacket
		.sink_valid         (router_src_valid),                                                         //          .valid
		.src0_ready         (cmd_demux_src0_ready),                                                     //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                                     //          .valid
		.src0_data          (cmd_demux_src0_data),                                                      //          .data
		.src0_channel       (cmd_demux_src0_channel),                                                   //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                                             //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                                                //          .endofpacket
	);

	lab1_system_mm_interconnect_1_cmd_demux cmd_demux_001 (
		.clk                (System_PLL_sys_clk_clk),                                                   //       clk.clk
		.reset              (ARM_A9_HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                                                     //      sink.ready
		.sink_channel       (router_001_src_channel),                                                   //          .channel
		.sink_data          (router_001_src_data),                                                      //          .data
		.sink_startofpacket (router_001_src_startofpacket),                                             //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                                               //          .endofpacket
		.sink_valid         (router_001_src_valid),                                                     //          .valid
		.src0_ready         (cmd_demux_001_src0_ready),                                                 //      src0.ready
		.src0_valid         (cmd_demux_001_src0_valid),                                                 //          .valid
		.src0_data          (cmd_demux_001_src0_data),                                                  //          .data
		.src0_channel       (cmd_demux_001_src0_channel),                                               //          .channel
		.src0_startofpacket (cmd_demux_001_src0_startofpacket),                                         //          .startofpacket
		.src0_endofpacket   (cmd_demux_001_src0_endofpacket)                                            //          .endofpacket
	);

	lab1_system_mm_interconnect_1_cmd_mux cmd_mux (
		.clk                 (System_PLL_sys_clk_clk),                              //       clk.clk
		.reset               (axi4_lite_booth_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                   //       src.ready
		.src_valid           (cmd_mux_src_valid),                                   //          .valid
		.src_data            (cmd_mux_src_data),                                    //          .data
		.src_channel         (cmd_mux_src_channel),                                 //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                           //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                             //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                                //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                                //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                              //          .channel
		.sink0_data          (cmd_demux_src0_data),                                 //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                        //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                           //          .endofpacket
	);

	lab1_system_mm_interconnect_1_cmd_mux cmd_mux_001 (
		.clk                 (System_PLL_sys_clk_clk),                              //       clk.clk
		.reset               (axi4_lite_booth_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_001_src_ready),                               //       src.ready
		.src_valid           (cmd_mux_001_src_valid),                               //          .valid
		.src_data            (cmd_mux_001_src_data),                                //          .data
		.src_channel         (cmd_mux_001_src_channel),                             //          .channel
		.src_startofpacket   (cmd_mux_001_src_startofpacket),                       //          .startofpacket
		.src_endofpacket     (cmd_mux_001_src_endofpacket),                         //          .endofpacket
		.sink0_ready         (cmd_demux_001_src0_ready),                            //     sink0.ready
		.sink0_valid         (cmd_demux_001_src0_valid),                            //          .valid
		.sink0_channel       (cmd_demux_001_src0_channel),                          //          .channel
		.sink0_data          (cmd_demux_001_src0_data),                             //          .data
		.sink0_startofpacket (cmd_demux_001_src0_startofpacket),                    //          .startofpacket
		.sink0_endofpacket   (cmd_demux_001_src0_endofpacket)                       //          .endofpacket
	);

	lab1_system_mm_interconnect_1_cmd_demux rsp_demux (
		.clk                (System_PLL_sys_clk_clk),                              //       clk.clk
		.reset              (axi4_lite_booth_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_002_src_ready),                                //      sink.ready
		.sink_channel       (router_002_src_channel),                              //          .channel
		.sink_data          (router_002_src_data),                                 //          .data
		.sink_startofpacket (router_002_src_startofpacket),                        //          .startofpacket
		.sink_endofpacket   (router_002_src_endofpacket),                          //          .endofpacket
		.sink_valid         (router_002_src_valid),                                //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                //          .valid
		.src0_data          (rsp_demux_src0_data),                                 //          .data
		.src0_channel       (rsp_demux_src0_channel),                              //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                        //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                           //          .endofpacket
	);

	lab1_system_mm_interconnect_1_cmd_demux rsp_demux_001 (
		.clk                (System_PLL_sys_clk_clk),                              //       clk.clk
		.reset              (axi4_lite_booth_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_003_src_ready),                                //      sink.ready
		.sink_channel       (router_003_src_channel),                              //          .channel
		.sink_data          (router_003_src_data),                                 //          .data
		.sink_startofpacket (router_003_src_startofpacket),                        //          .startofpacket
		.sink_endofpacket   (router_003_src_endofpacket),                          //          .endofpacket
		.sink_valid         (router_003_src_valid),                                //          .valid
		.src0_ready         (rsp_demux_001_src0_ready),                            //      src0.ready
		.src0_valid         (rsp_demux_001_src0_valid),                            //          .valid
		.src0_data          (rsp_demux_001_src0_data),                             //          .data
		.src0_channel       (rsp_demux_001_src0_channel),                          //          .channel
		.src0_startofpacket (rsp_demux_001_src0_startofpacket),                    //          .startofpacket
		.src0_endofpacket   (rsp_demux_001_src0_endofpacket)                       //          .endofpacket
	);

	lab1_system_mm_interconnect_1_rsp_mux rsp_mux (
		.clk                 (System_PLL_sys_clk_clk),                                                   //       clk.clk
		.reset               (ARM_A9_HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                                        //       src.ready
		.src_valid           (rsp_mux_src_valid),                                                        //          .valid
		.src_data            (rsp_mux_src_data),                                                         //          .data
		.src_channel         (rsp_mux_src_channel),                                                      //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                                                //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                                  //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                                                     //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                                                     //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                                                   //          .channel
		.sink0_data          (rsp_demux_src0_data),                                                      //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                                             //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                                                //          .endofpacket
	);

	lab1_system_mm_interconnect_1_rsp_mux rsp_mux_001 (
		.clk                 (System_PLL_sys_clk_clk),                                                   //       clk.clk
		.reset               (ARM_A9_HPS_h2f_lw_axi_master_agent_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_001_src_ready),                                                    //       src.ready
		.src_valid           (rsp_mux_001_src_valid),                                                    //          .valid
		.src_data            (rsp_mux_001_src_data),                                                     //          .data
		.src_channel         (rsp_mux_001_src_channel),                                                  //          .channel
		.src_startofpacket   (rsp_mux_001_src_startofpacket),                                            //          .startofpacket
		.src_endofpacket     (rsp_mux_001_src_endofpacket),                                              //          .endofpacket
		.sink0_ready         (rsp_demux_001_src0_ready),                                                 //     sink0.ready
		.sink0_valid         (rsp_demux_001_src0_valid),                                                 //          .valid
		.sink0_channel       (rsp_demux_001_src0_channel),                                               //          .channel
		.sink0_data          (rsp_demux_001_src0_data),                                                  //          .data
		.sink0_startofpacket (rsp_demux_001_src0_startofpacket),                                         //          .startofpacket
		.sink0_endofpacket   (rsp_demux_001_src0_endofpacket)                                            //          .endofpacket
	);

endmodule
