// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2021.1/950854 Production Release
//  HLS Date:       Mon Aug  2 21:36:02 PDT 2021
// 
//  Generated by:   andreu.roca.montserrat@c5c4
//  Generated date: Thu Nov 21 17:53:04 2024
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module mult_add_pipeline_core_core_fsm (
  clk, rst, core_wen, fsm_output
);
  input clk;
  input rst;
  input core_wen;
  output [1:0] fsm_output;
  reg [1:0] fsm_output;


  // FSM State Type Declaration for mult_add_pipeline_core_core_fsm_1
  parameter
    core_rlp_C_0 = 1'd0,
    main_C_0 = 1'd1;

  reg  state_var;
  reg  state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : mult_add_pipeline_core_core_fsm_1
    case (state_var)
      main_C_0 : begin
        fsm_output = 2'b10;
        state_var_NS = main_C_0;
      end
      // core_rlp_C_0
      default : begin
        fsm_output = 2'b01;
        state_var_NS = main_C_0;
      end
    endcase
  end

  always @(posedge clk) begin
    if ( rst ) begin
      state_var <= core_rlp_C_0;
    end
    else if ( core_wen ) begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_staller
// ------------------------------------------------------------------


module mult_add_pipeline_core_staller (
  clk, rst, core_wen, core_wten, a_rsci_wen_comp, b_rsci_wen_comp, c_rsci_wen_comp,
      result_rsci_wen_comp, a_rsci_wen_comp_pff, b_rsci_wen_comp_pff, c_rsci_wen_comp_pff,
      result_rsci_wen_comp_pff
);
  input clk;
  input rst;
  output core_wen;
  output core_wten;
  reg core_wten;
  input a_rsci_wen_comp;
  input b_rsci_wen_comp;
  input c_rsci_wen_comp;
  input result_rsci_wen_comp;
  input a_rsci_wen_comp_pff;
  input b_rsci_wen_comp_pff;
  input c_rsci_wen_comp_pff;
  input result_rsci_wen_comp_pff;



  // Interconnect Declarations for Component Instantiations 
  assign core_wen = a_rsci_wen_comp_pff & b_rsci_wen_comp_pff & c_rsci_wen_comp_pff
      & result_rsci_wen_comp_pff;
  always @(posedge clk) begin
    if ( rst ) begin
      core_wten <= 1'b0;
    end
    else begin
      core_wten <= ~(a_rsci_wen_comp & b_rsci_wen_comp & c_rsci_wen_comp & result_rsci_wen_comp);
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_gain_adjust_rsc_triosy_obj_gain_adjust_rsc_triosy_wait_ctrl
// ------------------------------------------------------------------


module mult_add_pipeline_core_gain_adjust_rsc_triosy_obj_gain_adjust_rsc_triosy_wait_ctrl
    (
  core_wten, gain_adjust_rsc_triosy_obj_iswt0, gain_adjust_rsc_triosy_obj_biwt
);
  input core_wten;
  input gain_adjust_rsc_triosy_obj_iswt0;
  output gain_adjust_rsc_triosy_obj_biwt;



  // Interconnect Declarations for Component Instantiations 
  assign gain_adjust_rsc_triosy_obj_biwt = (~ core_wten) & gain_adjust_rsc_triosy_obj_iswt0;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_gain_rsc_triosy_obj_gain_rsc_triosy_wait_ctrl
// ------------------------------------------------------------------


module mult_add_pipeline_core_gain_rsc_triosy_obj_gain_rsc_triosy_wait_ctrl (
  core_wten, gain_rsc_triosy_obj_iswt0, gain_rsc_triosy_obj_biwt
);
  input core_wten;
  input gain_rsc_triosy_obj_iswt0;
  output gain_rsc_triosy_obj_biwt;



  // Interconnect Declarations for Component Instantiations 
  assign gain_rsc_triosy_obj_biwt = (~ core_wten) & gain_rsc_triosy_obj_iswt0;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_result_rsci_result_wait_dp
// ------------------------------------------------------------------


module mult_add_pipeline_core_result_rsci_result_wait_dp (
  clk, rst, result_rsci_oswt, result_rsci_wen_comp, result_rsci_biwt, result_rsci_bdwt,
      result_rsci_bcwt, result_rsci_wen_comp_pff, result_rsci_oswt_pff, result_rsci_biwt_pff,
      result_rsci_bcwt_pff
);
  input clk;
  input rst;
  input result_rsci_oswt;
  output result_rsci_wen_comp;
  input result_rsci_biwt;
  input result_rsci_bdwt;
  output result_rsci_bcwt;
  output result_rsci_wen_comp_pff;
  input result_rsci_oswt_pff;
  input result_rsci_biwt_pff;
  output result_rsci_bcwt_pff;


  // Interconnect Declarations
  reg result_rsci_bcwt_reg;
  wire nor_rmff;


  // Interconnect Declarations for Component Instantiations 
  assign nor_rmff = ~((~(result_rsci_bcwt | result_rsci_biwt)) | result_rsci_bdwt);
  assign result_rsci_wen_comp = (~ result_rsci_oswt) | result_rsci_biwt | result_rsci_bcwt;
  assign result_rsci_wen_comp_pff = (~ result_rsci_oswt_pff) | result_rsci_biwt_pff
      | result_rsci_bcwt_pff;
  assign result_rsci_bcwt = result_rsci_bcwt_reg;
  assign result_rsci_bcwt_pff = nor_rmff;
  always @(posedge clk) begin
    if ( rst ) begin
      result_rsci_bcwt_reg <= 1'b0;
    end
    else begin
      result_rsci_bcwt_reg <= nor_rmff;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_result_rsci_result_wait_ctrl
// ------------------------------------------------------------------


module mult_add_pipeline_core_result_rsci_result_wait_ctrl (
  core_wen, result_rsci_oswt, result_rsci_irdy_oreg, result_rsci_biwt, result_rsci_bdwt,
      result_rsci_bcwt, result_rsci_ivld_core_sct, result_rsci_biwt_pff, result_rsci_oswt_pff,
      result_rsci_bcwt_pff, result_rsci_irdy_oreg_pff
);
  input core_wen;
  input result_rsci_oswt;
  input result_rsci_irdy_oreg;
  output result_rsci_biwt;
  output result_rsci_bdwt;
  input result_rsci_bcwt;
  output result_rsci_ivld_core_sct;
  output result_rsci_biwt_pff;
  input result_rsci_oswt_pff;
  input result_rsci_bcwt_pff;
  input result_rsci_irdy_oreg_pff;


  // Interconnect Declarations
  wire result_rsci_ogwt;


  // Interconnect Declarations for Component Instantiations 
  assign result_rsci_bdwt = result_rsci_oswt & core_wen;
  assign result_rsci_ogwt = result_rsci_oswt & (~ result_rsci_bcwt);
  assign result_rsci_ivld_core_sct = result_rsci_ogwt;
  assign result_rsci_biwt = result_rsci_ogwt & result_rsci_irdy_oreg;
  assign result_rsci_biwt_pff = result_rsci_oswt_pff & (~ result_rsci_bcwt_pff) &
      result_rsci_irdy_oreg_pff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_c_rsci_c_wait_dp
// ------------------------------------------------------------------


module mult_add_pipeline_core_c_rsci_c_wait_dp (
  clk, rst, c_rsci_oswt, c_rsci_wen_comp, c_rsci_idat_mxwt, c_rsci_biwt, c_rsci_bdwt,
      c_rsci_bcwt, c_rsci_idat, c_rsci_wen_comp_pff, c_rsci_oswt_pff, c_rsci_biwt_pff,
      c_rsci_bcwt_pff
);
  input clk;
  input rst;
  input c_rsci_oswt;
  output c_rsci_wen_comp;
  output [24:0] c_rsci_idat_mxwt;
  input c_rsci_biwt;
  input c_rsci_bdwt;
  output c_rsci_bcwt;
  input [24:0] c_rsci_idat;
  output c_rsci_wen_comp_pff;
  input c_rsci_oswt_pff;
  input c_rsci_biwt_pff;
  output c_rsci_bcwt_pff;


  // Interconnect Declarations
  reg [24:0] c_rsci_idat_bfwt;
  reg c_rsci_bcwt_reg;
  wire sum_nor_rmff;


  // Interconnect Declarations for Component Instantiations 
  assign sum_nor_rmff = ~((~(c_rsci_bcwt | c_rsci_biwt)) | c_rsci_bdwt);
  assign c_rsci_idat_mxwt = MUX_v_25_2_2(c_rsci_idat, c_rsci_idat_bfwt, c_rsci_bcwt);
  assign c_rsci_wen_comp = (~ c_rsci_oswt) | c_rsci_biwt | c_rsci_bcwt;
  assign c_rsci_wen_comp_pff = (~ c_rsci_oswt_pff) | c_rsci_biwt_pff | c_rsci_bcwt_pff;
  assign c_rsci_bcwt = c_rsci_bcwt_reg;
  assign c_rsci_bcwt_pff = sum_nor_rmff;
  always @(posedge clk) begin
    if ( rst ) begin
      c_rsci_bcwt_reg <= 1'b0;
    end
    else begin
      c_rsci_bcwt_reg <= sum_nor_rmff;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      c_rsci_idat_bfwt <= 25'b0000000000000000000000000;
    end
    else if ( c_rsci_biwt ) begin
      c_rsci_idat_bfwt <= c_rsci_idat;
    end
  end

  function automatic [24:0] MUX_v_25_2_2;
    input [24:0] input_0;
    input [24:0] input_1;
    input  sel;
    reg [24:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_25_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_c_rsci_c_wait_ctrl
// ------------------------------------------------------------------


module mult_add_pipeline_core_c_rsci_c_wait_ctrl (
  core_wen, c_rsci_oswt, c_rsci_ivld_oreg, c_rsci_biwt, c_rsci_bdwt, c_rsci_bcwt,
      c_rsci_irdy_core_sct, c_rsci_biwt_pff, c_rsci_oswt_pff, c_rsci_bcwt_pff, c_rsci_ivld_oreg_pff
);
  input core_wen;
  input c_rsci_oswt;
  input c_rsci_ivld_oreg;
  output c_rsci_biwt;
  output c_rsci_bdwt;
  input c_rsci_bcwt;
  output c_rsci_irdy_core_sct;
  output c_rsci_biwt_pff;
  input c_rsci_oswt_pff;
  input c_rsci_bcwt_pff;
  input c_rsci_ivld_oreg_pff;


  // Interconnect Declarations
  wire c_rsci_ogwt;


  // Interconnect Declarations for Component Instantiations 
  assign c_rsci_bdwt = c_rsci_oswt & core_wen;
  assign c_rsci_ogwt = c_rsci_oswt & (~ c_rsci_bcwt);
  assign c_rsci_irdy_core_sct = c_rsci_ogwt;
  assign c_rsci_biwt = c_rsci_ogwt & c_rsci_ivld_oreg;
  assign c_rsci_biwt_pff = c_rsci_oswt_pff & (~ c_rsci_bcwt_pff) & c_rsci_ivld_oreg_pff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_b_rsci_b_wait_dp
// ------------------------------------------------------------------


module mult_add_pipeline_core_b_rsci_b_wait_dp (
  clk, rst, b_rsci_oswt, b_rsci_wen_comp, b_rsci_idat_mxwt, b_rsci_biwt, b_rsci_bdwt,
      b_rsci_bcwt, b_rsci_idat, b_rsci_wen_comp_pff, b_rsci_oswt_pff, b_rsci_biwt_pff,
      b_rsci_bcwt_pff
);
  input clk;
  input rst;
  input b_rsci_oswt;
  output b_rsci_wen_comp;
  output [13:0] b_rsci_idat_mxwt;
  input b_rsci_biwt;
  input b_rsci_bdwt;
  output b_rsci_bcwt;
  input [13:0] b_rsci_idat;
  output b_rsci_wen_comp_pff;
  input b_rsci_oswt_pff;
  input b_rsci_biwt_pff;
  output b_rsci_bcwt_pff;


  // Interconnect Declarations
  reg [13:0] b_rsci_idat_bfwt;
  reg b_rsci_bcwt_reg;
  wire product_nor_2_rmff;


  // Interconnect Declarations for Component Instantiations 
  assign product_nor_2_rmff = ~((~(b_rsci_bcwt | b_rsci_biwt)) | b_rsci_bdwt);
  assign b_rsci_idat_mxwt = MUX_v_14_2_2(b_rsci_idat, b_rsci_idat_bfwt, b_rsci_bcwt);
  assign b_rsci_wen_comp = (~ b_rsci_oswt) | b_rsci_biwt | b_rsci_bcwt;
  assign b_rsci_wen_comp_pff = (~ b_rsci_oswt_pff) | b_rsci_biwt_pff | b_rsci_bcwt_pff;
  assign b_rsci_bcwt = b_rsci_bcwt_reg;
  assign b_rsci_bcwt_pff = product_nor_2_rmff;
  always @(posedge clk) begin
    if ( rst ) begin
      b_rsci_bcwt_reg <= 1'b0;
    end
    else begin
      b_rsci_bcwt_reg <= product_nor_2_rmff;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      b_rsci_idat_bfwt <= 14'b00000000000000;
    end
    else if ( b_rsci_biwt ) begin
      b_rsci_idat_bfwt <= b_rsci_idat;
    end
  end

  function automatic [13:0] MUX_v_14_2_2;
    input [13:0] input_0;
    input [13:0] input_1;
    input  sel;
    reg [13:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_14_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_b_rsci_b_wait_ctrl
// ------------------------------------------------------------------


module mult_add_pipeline_core_b_rsci_b_wait_ctrl (
  core_wen, b_rsci_oswt, b_rsci_ivld_oreg, b_rsci_biwt, b_rsci_bdwt, b_rsci_bcwt,
      b_rsci_irdy_core_sct, b_rsci_biwt_pff, b_rsci_oswt_pff, b_rsci_bcwt_pff, b_rsci_ivld_oreg_pff
);
  input core_wen;
  input b_rsci_oswt;
  input b_rsci_ivld_oreg;
  output b_rsci_biwt;
  output b_rsci_bdwt;
  input b_rsci_bcwt;
  output b_rsci_irdy_core_sct;
  output b_rsci_biwt_pff;
  input b_rsci_oswt_pff;
  input b_rsci_bcwt_pff;
  input b_rsci_ivld_oreg_pff;


  // Interconnect Declarations
  wire b_rsci_ogwt;


  // Interconnect Declarations for Component Instantiations 
  assign b_rsci_bdwt = b_rsci_oswt & core_wen;
  assign b_rsci_ogwt = b_rsci_oswt & (~ b_rsci_bcwt);
  assign b_rsci_irdy_core_sct = b_rsci_ogwt;
  assign b_rsci_biwt = b_rsci_ogwt & b_rsci_ivld_oreg;
  assign b_rsci_biwt_pff = b_rsci_oswt_pff & (~ b_rsci_bcwt_pff) & b_rsci_ivld_oreg_pff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_wait_dp
// ------------------------------------------------------------------


module mult_add_pipeline_core_wait_dp (
  clk, rst, operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z, product_mul_cmp_z,
      core_wen, a_rsci_ivld, a_rsci_ivld_oreg, b_rsci_ivld, b_rsci_ivld_oreg, c_rsci_ivld,
      c_rsci_ivld_oreg, result_rsci_irdy, result_rsci_irdy_oreg, operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z_oreg,
      product_mul_cmp_z_oreg
);
  input clk;
  input rst;
  input [33:0] operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z;
  input [24:0] product_mul_cmp_z;
  input core_wen;
  input a_rsci_ivld;
  output a_rsci_ivld_oreg;
  input b_rsci_ivld;
  output b_rsci_ivld_oreg;
  input c_rsci_ivld;
  output c_rsci_ivld_oreg;
  input result_rsci_irdy;
  output result_rsci_irdy_oreg;
  output [25:0] operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z_oreg;
  output [24:0] product_mul_cmp_z_oreg;
  reg [24:0] product_mul_cmp_z_oreg;


  // Interconnect Declarations
  reg a_rsci_ivld_oreg_rneg;
  reg b_rsci_ivld_oreg_rneg;
  reg c_rsci_ivld_oreg_rneg;
  reg result_rsci_irdy_oreg_rneg;
  reg [25:0] operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z_oreg_pconst_33_8;


  // Interconnect Declarations for Component Instantiations 
  assign operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z_oreg = operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z_oreg_pconst_33_8;
  assign a_rsci_ivld_oreg = ~ a_rsci_ivld_oreg_rneg;
  assign b_rsci_ivld_oreg = ~ b_rsci_ivld_oreg_rneg;
  assign c_rsci_ivld_oreg = ~ c_rsci_ivld_oreg_rneg;
  assign result_rsci_irdy_oreg = ~ result_rsci_irdy_oreg_rneg;
  always @(posedge clk) begin
    if ( rst ) begin
      a_rsci_ivld_oreg_rneg <= 1'b0;
      b_rsci_ivld_oreg_rneg <= 1'b0;
      c_rsci_ivld_oreg_rneg <= 1'b0;
      result_rsci_irdy_oreg_rneg <= 1'b0;
    end
    else begin
      a_rsci_ivld_oreg_rneg <= ~ a_rsci_ivld;
      b_rsci_ivld_oreg_rneg <= ~ b_rsci_ivld;
      c_rsci_ivld_oreg_rneg <= ~ c_rsci_ivld;
      result_rsci_irdy_oreg_rneg <= ~ result_rsci_irdy;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z_oreg_pconst_33_8 <= 26'b00000000000000000000000000;
      product_mul_cmp_z_oreg <= 25'b0000000000000000000000000;
    end
    else if ( core_wen ) begin
      operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z_oreg_pconst_33_8 <= operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z[33:8];
      product_mul_cmp_z_oreg <= product_mul_cmp_z;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_a_rsci_a_wait_dp
// ------------------------------------------------------------------


module mult_add_pipeline_core_a_rsci_a_wait_dp (
  clk, rst, a_rsci_oswt, a_rsci_wen_comp, a_rsci_idat_mxwt, a_rsci_biwt, a_rsci_bdwt,
      a_rsci_bcwt, a_rsci_idat, a_rsci_wen_comp_pff, a_rsci_oswt_pff, a_rsci_biwt_pff,
      a_rsci_bcwt_pff
);
  input clk;
  input rst;
  input a_rsci_oswt;
  output a_rsci_wen_comp;
  output [10:0] a_rsci_idat_mxwt;
  input a_rsci_biwt;
  input a_rsci_bdwt;
  output a_rsci_bcwt;
  input [10:0] a_rsci_idat;
  output a_rsci_wen_comp_pff;
  input a_rsci_oswt_pff;
  input a_rsci_biwt_pff;
  output a_rsci_bcwt_pff;


  // Interconnect Declarations
  reg [10:0] a_rsci_idat_bfwt;
  reg a_rsci_bcwt_reg;
  wire product_nor_rmff;


  // Interconnect Declarations for Component Instantiations 
  assign product_nor_rmff = ~((~(a_rsci_bcwt | a_rsci_biwt)) | a_rsci_bdwt);
  assign a_rsci_idat_mxwt = MUX_v_11_2_2(a_rsci_idat, a_rsci_idat_bfwt, a_rsci_bcwt);
  assign a_rsci_wen_comp = (~ a_rsci_oswt) | a_rsci_biwt | a_rsci_bcwt;
  assign a_rsci_wen_comp_pff = (~ a_rsci_oswt_pff) | a_rsci_biwt_pff | a_rsci_bcwt_pff;
  assign a_rsci_bcwt = a_rsci_bcwt_reg;
  assign a_rsci_bcwt_pff = product_nor_rmff;
  always @(posedge clk) begin
    if ( rst ) begin
      a_rsci_bcwt_reg <= 1'b0;
    end
    else begin
      a_rsci_bcwt_reg <= product_nor_rmff;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      a_rsci_idat_bfwt <= 11'b00000000000;
    end
    else if ( a_rsci_biwt ) begin
      a_rsci_idat_bfwt <= a_rsci_idat;
    end
  end

  function automatic [10:0] MUX_v_11_2_2;
    input [10:0] input_0;
    input [10:0] input_1;
    input  sel;
    reg [10:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_11_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_a_rsci_a_wait_ctrl
// ------------------------------------------------------------------


module mult_add_pipeline_core_a_rsci_a_wait_ctrl (
  core_wen, a_rsci_oswt, a_rsci_ivld_oreg, a_rsci_biwt, a_rsci_bdwt, a_rsci_bcwt,
      a_rsci_irdy_core_sct, a_rsci_biwt_pff, a_rsci_oswt_pff, a_rsci_bcwt_pff, a_rsci_ivld_oreg_pff
);
  input core_wen;
  input a_rsci_oswt;
  input a_rsci_ivld_oreg;
  output a_rsci_biwt;
  output a_rsci_bdwt;
  input a_rsci_bcwt;
  output a_rsci_irdy_core_sct;
  output a_rsci_biwt_pff;
  input a_rsci_oswt_pff;
  input a_rsci_bcwt_pff;
  input a_rsci_ivld_oreg_pff;


  // Interconnect Declarations
  wire a_rsci_ogwt;


  // Interconnect Declarations for Component Instantiations 
  assign a_rsci_bdwt = a_rsci_oswt & core_wen;
  assign a_rsci_ogwt = a_rsci_oswt & (~ a_rsci_bcwt);
  assign a_rsci_irdy_core_sct = a_rsci_ogwt;
  assign a_rsci_biwt = a_rsci_ogwt & a_rsci_ivld_oreg;
  assign a_rsci_biwt_pff = a_rsci_oswt_pff & (~ a_rsci_bcwt_pff) & a_rsci_ivld_oreg_pff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_gain_adjust_rsc_triosy_obj
// ------------------------------------------------------------------


module mult_add_pipeline_core_gain_adjust_rsc_triosy_obj (
  gain_adjust_rsc_triosy_lz, core_wten, gain_adjust_rsc_triosy_obj_iswt0
);
  output gain_adjust_rsc_triosy_lz;
  input core_wten;
  input gain_adjust_rsc_triosy_obj_iswt0;


  // Interconnect Declarations
  wire gain_adjust_rsc_triosy_obj_biwt;


  // Interconnect Declarations for Component Instantiations 
  mgc_io_sync_v2 #(.valid(32'sd0)) gain_adjust_rsc_triosy_obj (
      .ld(gain_adjust_rsc_triosy_obj_biwt),
      .lz(gain_adjust_rsc_triosy_lz)
    );
  mult_add_pipeline_core_gain_adjust_rsc_triosy_obj_gain_adjust_rsc_triosy_wait_ctrl
      mult_add_pipeline_core_gain_adjust_rsc_triosy_obj_gain_adjust_rsc_triosy_wait_ctrl_inst
      (
      .core_wten(core_wten),
      .gain_adjust_rsc_triosy_obj_iswt0(gain_adjust_rsc_triosy_obj_iswt0),
      .gain_adjust_rsc_triosy_obj_biwt(gain_adjust_rsc_triosy_obj_biwt)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_gain_rsc_triosy_obj
// ------------------------------------------------------------------


module mult_add_pipeline_core_gain_rsc_triosy_obj (
  gain_rsc_triosy_lz, core_wten, gain_rsc_triosy_obj_iswt0
);
  output gain_rsc_triosy_lz;
  input core_wten;
  input gain_rsc_triosy_obj_iswt0;


  // Interconnect Declarations
  wire gain_rsc_triosy_obj_biwt;


  // Interconnect Declarations for Component Instantiations 
  mgc_io_sync_v2 #(.valid(32'sd0)) gain_rsc_triosy_obj (
      .ld(gain_rsc_triosy_obj_biwt),
      .lz(gain_rsc_triosy_lz)
    );
  mult_add_pipeline_core_gain_rsc_triosy_obj_gain_rsc_triosy_wait_ctrl mult_add_pipeline_core_gain_rsc_triosy_obj_gain_rsc_triosy_wait_ctrl_inst
      (
      .core_wten(core_wten),
      .gain_rsc_triosy_obj_iswt0(gain_rsc_triosy_obj_iswt0),
      .gain_rsc_triosy_obj_biwt(gain_rsc_triosy_obj_biwt)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_result_rsci
// ------------------------------------------------------------------


module mult_add_pipeline_core_result_rsci (
  clk, rst, result_rsc_dat, result_rsc_vld, result_rsc_rdy, core_wen, result_rsci_oswt,
      result_rsci_wen_comp, result_rsci_irdy, result_rsci_irdy_oreg, result_rsci_idat,
      result_rsci_wen_comp_pff, result_rsci_oswt_pff, result_rsci_irdy_oreg_pff
);
  input clk;
  input rst;
  output [29:0] result_rsc_dat;
  output result_rsc_vld;
  input result_rsc_rdy;
  input core_wen;
  input result_rsci_oswt;
  output result_rsci_wen_comp;
  output result_rsci_irdy;
  input result_rsci_irdy_oreg;
  input [29:0] result_rsci_idat;
  output result_rsci_wen_comp_pff;
  input result_rsci_oswt_pff;
  input result_rsci_irdy_oreg_pff;


  // Interconnect Declarations
  wire result_rsci_biwt;
  wire result_rsci_bdwt;
  wire result_rsci_bcwt;
  wire result_rsci_ivld_core_sct;
  wire result_rsc_is_idle;
  wire result_rsci_wen_comp_reg;
  wire result_rsci_wen_comp_iff;
  wire result_rsci_biwt_iff;
  wire result_rsci_bcwt_iff;


  // Interconnect Declarations for Component Instantiations 
  wire [29:0] nl_result_rsci_idat;
  assign nl_result_rsci_idat = {(result_rsci_idat[29:4]) , 4'b0000};
  ccs_out_buf_wait_v5 #(.rscid(32'sd6),
  .width(32'sd30),
  .ph_clk(32'sd1),
  .ph_en(32'sd0),
  .ph_arst(32'sd0),
  .ph_srst(32'sd1),
  .rst_val(32'sd0)) result_rsci (
      .clk(clk),
      .en(1'b0),
      .arst(1'b1),
      .srst(rst),
      .irdy(result_rsci_irdy),
      .ivld(result_rsci_ivld_core_sct),
      .idat(nl_result_rsci_idat[29:0]),
      .rdy(result_rsc_rdy),
      .vld(result_rsc_vld),
      .dat(result_rsc_dat),
      .is_idle(result_rsc_is_idle)
    );
  mult_add_pipeline_core_result_rsci_result_wait_ctrl mult_add_pipeline_core_result_rsci_result_wait_ctrl_inst
      (
      .core_wen(core_wen),
      .result_rsci_oswt(result_rsci_oswt),
      .result_rsci_irdy_oreg(result_rsci_irdy_oreg),
      .result_rsci_biwt(result_rsci_biwt),
      .result_rsci_bdwt(result_rsci_bdwt),
      .result_rsci_bcwt(result_rsci_bcwt),
      .result_rsci_ivld_core_sct(result_rsci_ivld_core_sct),
      .result_rsci_biwt_pff(result_rsci_biwt_iff),
      .result_rsci_oswt_pff(result_rsci_oswt_pff),
      .result_rsci_bcwt_pff(result_rsci_bcwt_iff),
      .result_rsci_irdy_oreg_pff(result_rsci_irdy_oreg_pff)
    );
  mult_add_pipeline_core_result_rsci_result_wait_dp mult_add_pipeline_core_result_rsci_result_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .result_rsci_oswt(result_rsci_oswt),
      .result_rsci_wen_comp(result_rsci_wen_comp_reg),
      .result_rsci_biwt(result_rsci_biwt),
      .result_rsci_bdwt(result_rsci_bdwt),
      .result_rsci_bcwt(result_rsci_bcwt),
      .result_rsci_wen_comp_pff(result_rsci_wen_comp_iff),
      .result_rsci_oswt_pff(result_rsci_oswt_pff),
      .result_rsci_biwt_pff(result_rsci_biwt_iff),
      .result_rsci_bcwt_pff(result_rsci_bcwt_iff)
    );
  assign result_rsci_wen_comp = result_rsci_wen_comp_reg;
  assign result_rsci_wen_comp_pff = result_rsci_wen_comp_iff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_c_rsci
// ------------------------------------------------------------------


module mult_add_pipeline_core_c_rsci (
  clk, rst, c_rsc_dat, c_rsc_vld, c_rsc_rdy, core_wen, c_rsci_oswt, c_rsci_wen_comp,
      c_rsci_ivld, c_rsci_ivld_oreg, c_rsci_idat_mxwt, c_rsci_wen_comp_pff, c_rsci_oswt_pff,
      c_rsci_ivld_oreg_pff
);
  input clk;
  input rst;
  input [24:0] c_rsc_dat;
  input c_rsc_vld;
  output c_rsc_rdy;
  input core_wen;
  input c_rsci_oswt;
  output c_rsci_wen_comp;
  output c_rsci_ivld;
  input c_rsci_ivld_oreg;
  output [24:0] c_rsci_idat_mxwt;
  output c_rsci_wen_comp_pff;
  input c_rsci_oswt_pff;
  input c_rsci_ivld_oreg_pff;


  // Interconnect Declarations
  wire c_rsci_biwt;
  wire c_rsci_bdwt;
  wire c_rsci_bcwt;
  wire c_rsci_irdy_core_sct;
  wire [24:0] c_rsci_idat;
  wire c_rsc_is_idle;
  wire c_rsci_wen_comp_reg;
  wire c_rsci_wen_comp_iff;
  wire c_rsci_biwt_iff;
  wire c_rsci_bcwt_iff;


  // Interconnect Declarations for Component Instantiations 
  ccs_ctrl_in_buf_wait_v4 #(.rscid(32'sd3),
  .width(32'sd25),
  .ph_clk(32'sd1),
  .ph_en(32'sd0),
  .ph_arst(32'sd0),
  .ph_srst(32'sd1)) c_rsci (
      .clk(clk),
      .en(1'b0),
      .arst(1'b1),
      .srst(rst),
      .rdy(c_rsc_rdy),
      .vld(c_rsc_vld),
      .dat(c_rsc_dat),
      .irdy(c_rsci_irdy_core_sct),
      .ivld(c_rsci_ivld),
      .idat(c_rsci_idat),
      .is_idle(c_rsc_is_idle)
    );
  mult_add_pipeline_core_c_rsci_c_wait_ctrl mult_add_pipeline_core_c_rsci_c_wait_ctrl_inst
      (
      .core_wen(core_wen),
      .c_rsci_oswt(c_rsci_oswt),
      .c_rsci_ivld_oreg(c_rsci_ivld_oreg),
      .c_rsci_biwt(c_rsci_biwt),
      .c_rsci_bdwt(c_rsci_bdwt),
      .c_rsci_bcwt(c_rsci_bcwt),
      .c_rsci_irdy_core_sct(c_rsci_irdy_core_sct),
      .c_rsci_biwt_pff(c_rsci_biwt_iff),
      .c_rsci_oswt_pff(c_rsci_oswt_pff),
      .c_rsci_bcwt_pff(c_rsci_bcwt_iff),
      .c_rsci_ivld_oreg_pff(c_rsci_ivld_oreg_pff)
    );
  mult_add_pipeline_core_c_rsci_c_wait_dp mult_add_pipeline_core_c_rsci_c_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .c_rsci_oswt(c_rsci_oswt),
      .c_rsci_wen_comp(c_rsci_wen_comp_reg),
      .c_rsci_idat_mxwt(c_rsci_idat_mxwt),
      .c_rsci_biwt(c_rsci_biwt),
      .c_rsci_bdwt(c_rsci_bdwt),
      .c_rsci_bcwt(c_rsci_bcwt),
      .c_rsci_idat(c_rsci_idat),
      .c_rsci_wen_comp_pff(c_rsci_wen_comp_iff),
      .c_rsci_oswt_pff(c_rsci_oswt_pff),
      .c_rsci_biwt_pff(c_rsci_biwt_iff),
      .c_rsci_bcwt_pff(c_rsci_bcwt_iff)
    );
  assign c_rsci_wen_comp = c_rsci_wen_comp_reg;
  assign c_rsci_wen_comp_pff = c_rsci_wen_comp_iff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_b_rsci
// ------------------------------------------------------------------


module mult_add_pipeline_core_b_rsci (
  clk, rst, b_rsc_dat, b_rsc_vld, b_rsc_rdy, core_wen, b_rsci_oswt, b_rsci_wen_comp,
      b_rsci_ivld, b_rsci_ivld_oreg, b_rsci_idat_mxwt, b_rsci_wen_comp_pff, b_rsci_oswt_pff,
      b_rsci_ivld_oreg_pff
);
  input clk;
  input rst;
  input [13:0] b_rsc_dat;
  input b_rsc_vld;
  output b_rsc_rdy;
  input core_wen;
  input b_rsci_oswt;
  output b_rsci_wen_comp;
  output b_rsci_ivld;
  input b_rsci_ivld_oreg;
  output [13:0] b_rsci_idat_mxwt;
  output b_rsci_wen_comp_pff;
  input b_rsci_oswt_pff;
  input b_rsci_ivld_oreg_pff;


  // Interconnect Declarations
  wire b_rsci_biwt;
  wire b_rsci_bdwt;
  wire b_rsci_bcwt;
  wire b_rsci_irdy_core_sct;
  wire [13:0] b_rsci_idat;
  wire b_rsc_is_idle;
  wire b_rsci_wen_comp_reg;
  wire b_rsci_wen_comp_iff;
  wire b_rsci_biwt_iff;
  wire b_rsci_bcwt_iff;


  // Interconnect Declarations for Component Instantiations 
  ccs_ctrl_in_buf_wait_v4 #(.rscid(32'sd2),
  .width(32'sd14),
  .ph_clk(32'sd1),
  .ph_en(32'sd0),
  .ph_arst(32'sd0),
  .ph_srst(32'sd1)) b_rsci (
      .clk(clk),
      .en(1'b0),
      .arst(1'b1),
      .srst(rst),
      .rdy(b_rsc_rdy),
      .vld(b_rsc_vld),
      .dat(b_rsc_dat),
      .irdy(b_rsci_irdy_core_sct),
      .ivld(b_rsci_ivld),
      .idat(b_rsci_idat),
      .is_idle(b_rsc_is_idle)
    );
  mult_add_pipeline_core_b_rsci_b_wait_ctrl mult_add_pipeline_core_b_rsci_b_wait_ctrl_inst
      (
      .core_wen(core_wen),
      .b_rsci_oswt(b_rsci_oswt),
      .b_rsci_ivld_oreg(b_rsci_ivld_oreg),
      .b_rsci_biwt(b_rsci_biwt),
      .b_rsci_bdwt(b_rsci_bdwt),
      .b_rsci_bcwt(b_rsci_bcwt),
      .b_rsci_irdy_core_sct(b_rsci_irdy_core_sct),
      .b_rsci_biwt_pff(b_rsci_biwt_iff),
      .b_rsci_oswt_pff(b_rsci_oswt_pff),
      .b_rsci_bcwt_pff(b_rsci_bcwt_iff),
      .b_rsci_ivld_oreg_pff(b_rsci_ivld_oreg_pff)
    );
  mult_add_pipeline_core_b_rsci_b_wait_dp mult_add_pipeline_core_b_rsci_b_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .b_rsci_oswt(b_rsci_oswt),
      .b_rsci_wen_comp(b_rsci_wen_comp_reg),
      .b_rsci_idat_mxwt(b_rsci_idat_mxwt),
      .b_rsci_biwt(b_rsci_biwt),
      .b_rsci_bdwt(b_rsci_bdwt),
      .b_rsci_bcwt(b_rsci_bcwt),
      .b_rsci_idat(b_rsci_idat),
      .b_rsci_wen_comp_pff(b_rsci_wen_comp_iff),
      .b_rsci_oswt_pff(b_rsci_oswt_pff),
      .b_rsci_biwt_pff(b_rsci_biwt_iff),
      .b_rsci_bcwt_pff(b_rsci_bcwt_iff)
    );
  assign b_rsci_wen_comp = b_rsci_wen_comp_reg;
  assign b_rsci_wen_comp_pff = b_rsci_wen_comp_iff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core_a_rsci
// ------------------------------------------------------------------


module mult_add_pipeline_core_a_rsci (
  clk, rst, a_rsc_dat, a_rsc_vld, a_rsc_rdy, core_wen, a_rsci_oswt, a_rsci_wen_comp,
      a_rsci_ivld, a_rsci_ivld_oreg, a_rsci_idat_mxwt, a_rsci_wen_comp_pff, a_rsci_oswt_pff,
      a_rsci_ivld_oreg_pff
);
  input clk;
  input rst;
  input [10:0] a_rsc_dat;
  input a_rsc_vld;
  output a_rsc_rdy;
  input core_wen;
  input a_rsci_oswt;
  output a_rsci_wen_comp;
  output a_rsci_ivld;
  input a_rsci_ivld_oreg;
  output [10:0] a_rsci_idat_mxwt;
  output a_rsci_wen_comp_pff;
  input a_rsci_oswt_pff;
  input a_rsci_ivld_oreg_pff;


  // Interconnect Declarations
  wire a_rsci_biwt;
  wire a_rsci_bdwt;
  wire a_rsci_bcwt;
  wire a_rsci_irdy_core_sct;
  wire [10:0] a_rsci_idat;
  wire a_rsc_is_idle;
  wire a_rsci_wen_comp_reg;
  wire a_rsci_wen_comp_iff;
  wire a_rsci_biwt_iff;
  wire a_rsci_bcwt_iff;


  // Interconnect Declarations for Component Instantiations 
  ccs_ctrl_in_buf_wait_v4 #(.rscid(32'sd1),
  .width(32'sd11),
  .ph_clk(32'sd1),
  .ph_en(32'sd0),
  .ph_arst(32'sd0),
  .ph_srst(32'sd1)) a_rsci (
      .clk(clk),
      .en(1'b0),
      .arst(1'b1),
      .srst(rst),
      .rdy(a_rsc_rdy),
      .vld(a_rsc_vld),
      .dat(a_rsc_dat),
      .irdy(a_rsci_irdy_core_sct),
      .ivld(a_rsci_ivld),
      .idat(a_rsci_idat),
      .is_idle(a_rsc_is_idle)
    );
  mult_add_pipeline_core_a_rsci_a_wait_ctrl mult_add_pipeline_core_a_rsci_a_wait_ctrl_inst
      (
      .core_wen(core_wen),
      .a_rsci_oswt(a_rsci_oswt),
      .a_rsci_ivld_oreg(a_rsci_ivld_oreg),
      .a_rsci_biwt(a_rsci_biwt),
      .a_rsci_bdwt(a_rsci_bdwt),
      .a_rsci_bcwt(a_rsci_bcwt),
      .a_rsci_irdy_core_sct(a_rsci_irdy_core_sct),
      .a_rsci_biwt_pff(a_rsci_biwt_iff),
      .a_rsci_oswt_pff(a_rsci_oswt_pff),
      .a_rsci_bcwt_pff(a_rsci_bcwt_iff),
      .a_rsci_ivld_oreg_pff(a_rsci_ivld_oreg_pff)
    );
  mult_add_pipeline_core_a_rsci_a_wait_dp mult_add_pipeline_core_a_rsci_a_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .a_rsci_oswt(a_rsci_oswt),
      .a_rsci_wen_comp(a_rsci_wen_comp_reg),
      .a_rsci_idat_mxwt(a_rsci_idat_mxwt),
      .a_rsci_biwt(a_rsci_biwt),
      .a_rsci_bdwt(a_rsci_bdwt),
      .a_rsci_bcwt(a_rsci_bcwt),
      .a_rsci_idat(a_rsci_idat),
      .a_rsci_wen_comp_pff(a_rsci_wen_comp_iff),
      .a_rsci_oswt_pff(a_rsci_oswt_pff),
      .a_rsci_biwt_pff(a_rsci_biwt_iff),
      .a_rsci_bcwt_pff(a_rsci_bcwt_iff)
    );
  assign a_rsci_wen_comp = a_rsci_wen_comp_reg;
  assign a_rsci_wen_comp_pff = a_rsci_wen_comp_iff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline_core
// ------------------------------------------------------------------


module mult_add_pipeline_core (
  clk, rst, a_rsc_dat, a_rsc_vld, a_rsc_rdy, b_rsc_dat, b_rsc_vld, b_rsc_rdy, c_rsc_dat,
      c_rsc_vld, c_rsc_rdy, gain_rsc_dat, gain_rsc_triosy_lz, gain_adjust_rsc_dat,
      gain_adjust_rsc_triosy_lz, result_rsc_dat, result_rsc_vld, result_rsc_rdy,
      operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_a, operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b,
      operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z, product_mul_cmp_a, product_mul_cmp_b,
      product_mul_cmp_z
);
  input clk;
  input rst;
  input [10:0] a_rsc_dat;
  input a_rsc_vld;
  output a_rsc_rdy;
  input [13:0] b_rsc_dat;
  input b_rsc_vld;
  output b_rsc_rdy;
  input [24:0] c_rsc_dat;
  input c_rsc_vld;
  output c_rsc_rdy;
  input [9:0] gain_rsc_dat;
  output gain_rsc_triosy_lz;
  input gain_adjust_rsc_dat;
  output gain_adjust_rsc_triosy_lz;
  output [29:0] result_rsc_dat;
  output result_rsc_vld;
  input result_rsc_rdy;
  output [9:0] operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_a;
  reg [9:0] operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_a;
  output [25:0] operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b;
  input [33:0] operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z;
  output [10:0] product_mul_cmp_a;
  reg [10:0] product_mul_cmp_a;
  output [13:0] product_mul_cmp_b;
  reg [13:0] product_mul_cmp_b;
  input [24:0] product_mul_cmp_z;


  // Interconnect Declarations
  reg core_wen;
  wire core_wten;
  wire a_rsci_wen_comp;
  wire a_rsci_ivld;
  wire a_rsci_ivld_oreg;
  wire [10:0] a_rsci_idat_mxwt;
  wire b_rsci_wen_comp;
  wire b_rsci_ivld;
  wire b_rsci_ivld_oreg;
  wire [13:0] b_rsci_idat_mxwt;
  wire c_rsci_wen_comp;
  wire c_rsci_ivld;
  wire c_rsci_ivld_oreg;
  wire [24:0] c_rsci_idat_mxwt;
  wire [9:0] gain_rsci_idat;
  wire gain_adjust_rsci_idat;
  wire result_rsci_wen_comp;
  wire result_rsci_irdy;
  wire result_rsci_irdy_oreg;
  wire [25:0] operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z_oreg;
  wire [24:0] product_mul_cmp_z_oreg;
  reg [25:0] result_rsci_idat_29_4;
  wire [1:0] fsm_output;
  reg CHECK_io_read_gain_adjust_rsc_svs_st_3;
  reg main_stage_0_4;
  reg CHECK_io_read_gain_adjust_rsc_svs_st_1;
  reg main_stage_0_5;
  reg CHECK_io_read_gain_adjust_rsc_svs_4;
  reg reg_gain_adjust_rsc_triosy_obj_iswt0_cse;
  wire core_wen_rtff;
  reg reg_c_rsci_iswt0_tmp;
  reg reg_result_rsci_iswt0_tmp;
  wire a_rsci_wen_comp_iff;
  wire sum_mux_rmff;
  wire b_rsci_wen_comp_iff;
  wire c_rsci_wen_comp_iff;
  wire result_rsci_wen_comp_iff;
  wire mux_rmff;
  reg main_stage_0_3;
  reg [9:0] gain_sva_1;
  reg [9:0] gain_sva_2;
  reg [24:0] sum_c_tmp_sva_1;
  reg [24:0] sum_c_tmp_sva_2;
  reg [25:0] sum_sva_2;
  reg CHECK_io_read_gain_adjust_rsc_svs_st_2;
  reg [25:0] reg_operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b_cse;
  wire [26:0] nl_reg_operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b_cse;
  wire CHECK_and_1_cse;

  wire and_3_nl;

  // Interconnect Declarations for Component Instantiations 
  wire [29:0] nl_mult_add_pipeline_core_result_rsci_inst_result_rsci_idat;
  assign nl_mult_add_pipeline_core_result_rsci_inst_result_rsci_idat = {result_rsci_idat_29_4
      , 4'b0000};
  ccs_in_v1 #(.rscid(32'sd4),
  .width(32'sd10)) gain_rsci (
      .dat(gain_rsc_dat),
      .idat(gain_rsci_idat)
    );
  ccs_in_v1 #(.rscid(32'sd5),
  .width(32'sd1)) gain_adjust_rsci (
      .dat(gain_adjust_rsc_dat),
      .idat(gain_adjust_rsci_idat)
    );
  mult_add_pipeline_core_a_rsci mult_add_pipeline_core_a_rsci_inst (
      .clk(clk),
      .rst(rst),
      .a_rsc_dat(a_rsc_dat),
      .a_rsc_vld(a_rsc_vld),
      .a_rsc_rdy(a_rsc_rdy),
      .core_wen(core_wen),
      .a_rsci_oswt(reg_c_rsci_iswt0_tmp),
      .a_rsci_wen_comp(a_rsci_wen_comp),
      .a_rsci_ivld(a_rsci_ivld),
      .a_rsci_ivld_oreg(a_rsci_ivld_oreg),
      .a_rsci_idat_mxwt(a_rsci_idat_mxwt),
      .a_rsci_wen_comp_pff(a_rsci_wen_comp_iff),
      .a_rsci_oswt_pff(sum_mux_rmff),
      .a_rsci_ivld_oreg_pff(a_rsci_ivld)
    );
  mult_add_pipeline_core_wait_dp mult_add_pipeline_core_wait_dp_inst (
      .clk(clk),
      .rst(rst),
      .operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z(operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z),
      .product_mul_cmp_z(product_mul_cmp_z),
      .core_wen(core_wen),
      .a_rsci_ivld(a_rsci_ivld),
      .a_rsci_ivld_oreg(a_rsci_ivld_oreg),
      .b_rsci_ivld(b_rsci_ivld),
      .b_rsci_ivld_oreg(b_rsci_ivld_oreg),
      .c_rsci_ivld(c_rsci_ivld),
      .c_rsci_ivld_oreg(c_rsci_ivld_oreg),
      .result_rsci_irdy(result_rsci_irdy),
      .result_rsci_irdy_oreg(result_rsci_irdy_oreg),
      .operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z_oreg(operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z_oreg),
      .product_mul_cmp_z_oreg(product_mul_cmp_z_oreg)
    );
  mult_add_pipeline_core_b_rsci mult_add_pipeline_core_b_rsci_inst (
      .clk(clk),
      .rst(rst),
      .b_rsc_dat(b_rsc_dat),
      .b_rsc_vld(b_rsc_vld),
      .b_rsc_rdy(b_rsc_rdy),
      .core_wen(core_wen),
      .b_rsci_oswt(reg_c_rsci_iswt0_tmp),
      .b_rsci_wen_comp(b_rsci_wen_comp),
      .b_rsci_ivld(b_rsci_ivld),
      .b_rsci_ivld_oreg(b_rsci_ivld_oreg),
      .b_rsci_idat_mxwt(b_rsci_idat_mxwt),
      .b_rsci_wen_comp_pff(b_rsci_wen_comp_iff),
      .b_rsci_oswt_pff(sum_mux_rmff),
      .b_rsci_ivld_oreg_pff(b_rsci_ivld)
    );
  mult_add_pipeline_core_c_rsci mult_add_pipeline_core_c_rsci_inst (
      .clk(clk),
      .rst(rst),
      .c_rsc_dat(c_rsc_dat),
      .c_rsc_vld(c_rsc_vld),
      .c_rsc_rdy(c_rsc_rdy),
      .core_wen(core_wen),
      .c_rsci_oswt(reg_c_rsci_iswt0_tmp),
      .c_rsci_wen_comp(c_rsci_wen_comp),
      .c_rsci_ivld(c_rsci_ivld),
      .c_rsci_ivld_oreg(c_rsci_ivld_oreg),
      .c_rsci_idat_mxwt(c_rsci_idat_mxwt),
      .c_rsci_wen_comp_pff(c_rsci_wen_comp_iff),
      .c_rsci_oswt_pff(sum_mux_rmff),
      .c_rsci_ivld_oreg_pff(c_rsci_ivld)
    );
  mult_add_pipeline_core_result_rsci mult_add_pipeline_core_result_rsci_inst (
      .clk(clk),
      .rst(rst),
      .result_rsc_dat(result_rsc_dat),
      .result_rsc_vld(result_rsc_vld),
      .result_rsc_rdy(result_rsc_rdy),
      .core_wen(core_wen),
      .result_rsci_oswt(reg_result_rsci_iswt0_tmp),
      .result_rsci_wen_comp(result_rsci_wen_comp),
      .result_rsci_irdy(result_rsci_irdy),
      .result_rsci_irdy_oreg(result_rsci_irdy_oreg),
      .result_rsci_idat(nl_mult_add_pipeline_core_result_rsci_inst_result_rsci_idat[29:0]),
      .result_rsci_wen_comp_pff(result_rsci_wen_comp_iff),
      .result_rsci_oswt_pff(mux_rmff),
      .result_rsci_irdy_oreg_pff(result_rsci_irdy)
    );
  mult_add_pipeline_core_gain_rsc_triosy_obj mult_add_pipeline_core_gain_rsc_triosy_obj_inst
      (
      .gain_rsc_triosy_lz(gain_rsc_triosy_lz),
      .core_wten(core_wten),
      .gain_rsc_triosy_obj_iswt0(reg_gain_adjust_rsc_triosy_obj_iswt0_cse)
    );
  mult_add_pipeline_core_gain_adjust_rsc_triosy_obj mult_add_pipeline_core_gain_adjust_rsc_triosy_obj_inst
      (
      .gain_adjust_rsc_triosy_lz(gain_adjust_rsc_triosy_lz),
      .core_wten(core_wten),
      .gain_adjust_rsc_triosy_obj_iswt0(reg_gain_adjust_rsc_triosy_obj_iswt0_cse)
    );
  mult_add_pipeline_core_staller mult_add_pipeline_core_staller_inst (
      .clk(clk),
      .rst(rst),
      .core_wen(core_wen_rtff),
      .core_wten(core_wten),
      .a_rsci_wen_comp(a_rsci_wen_comp),
      .b_rsci_wen_comp(b_rsci_wen_comp),
      .c_rsci_wen_comp(c_rsci_wen_comp),
      .result_rsci_wen_comp(result_rsci_wen_comp),
      .a_rsci_wen_comp_pff(a_rsci_wen_comp_iff),
      .b_rsci_wen_comp_pff(b_rsci_wen_comp_iff),
      .c_rsci_wen_comp_pff(c_rsci_wen_comp_iff),
      .result_rsci_wen_comp_pff(result_rsci_wen_comp_iff)
    );
  mult_add_pipeline_core_core_fsm mult_add_pipeline_core_core_fsm_inst (
      .clk(clk),
      .rst(rst),
      .core_wen(core_wen),
      .fsm_output(fsm_output)
    );
  assign mux_rmff = MUX_s_1_2_2(reg_result_rsci_iswt0_tmp, main_stage_0_5, core_wen);
  assign sum_mux_rmff = reg_c_rsci_iswt0_tmp | core_wen;
  assign operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b = reg_operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b_cse;
  assign CHECK_and_1_cse = core_wen & reg_gain_adjust_rsc_triosy_obj_iswt0_cse;
  always @(posedge clk) begin
    if ( rst ) begin
      result_rsci_idat_29_4 <= 26'b00000000000000000000000000;
    end
    else if ( core_wen & main_stage_0_5 ) begin
      result_rsci_idat_29_4 <= MUX_v_26_2_2(operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z_oreg,
          sum_sva_2, and_3_nl);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      reg_gain_adjust_rsc_triosy_obj_iswt0_cse <= 1'b0;
      reg_result_rsci_iswt0_tmp <= 1'b0;
      product_mul_cmp_b <= 14'b00000000000000;
      product_mul_cmp_a <= 11'b00000000000;
      reg_operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b_cse <= 26'b00000000000000000000000000;
      operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_a <= 10'b0000000000;
      main_stage_0_3 <= 1'b0;
      main_stage_0_5 <= 1'b0;
      CHECK_io_read_gain_adjust_rsc_svs_st_1 <= 1'b0;
      sum_c_tmp_sva_1 <= 25'b0000000000000000000000000;
      main_stage_0_4 <= 1'b0;
    end
    else if ( core_wen ) begin
      reg_gain_adjust_rsc_triosy_obj_iswt0_cse <= fsm_output[1];
      reg_result_rsci_iswt0_tmp <= mux_rmff;
      product_mul_cmp_b <= b_rsci_idat_mxwt;
      product_mul_cmp_a <= a_rsci_idat_mxwt;
      reg_operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b_cse <= nl_reg_operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b_cse[25:0];
      operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_a <= gain_sva_2;
      main_stage_0_3 <= reg_gain_adjust_rsc_triosy_obj_iswt0_cse;
      main_stage_0_5 <= main_stage_0_4;
      CHECK_io_read_gain_adjust_rsc_svs_st_1 <= gain_adjust_rsci_idat;
      sum_c_tmp_sva_1 <= c_rsci_idat_mxwt;
      main_stage_0_4 <= main_stage_0_3;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      reg_c_rsci_iswt0_tmp <= 1'b0;
      core_wen <= 1'b1;
    end
    else begin
      reg_c_rsci_iswt0_tmp <= sum_mux_rmff;
      core_wen <= core_wen_rtff;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      sum_sva_2 <= 26'b00000000000000000000000000;
    end
    else if ( core_wen & main_stage_0_4 & (~ CHECK_io_read_gain_adjust_rsc_svs_st_3)
        ) begin
      sum_sva_2 <= reg_operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b_cse;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      CHECK_io_read_gain_adjust_rsc_svs_4 <= 1'b0;
    end
    else if ( core_wen & main_stage_0_4 ) begin
      CHECK_io_read_gain_adjust_rsc_svs_4 <= CHECK_io_read_gain_adjust_rsc_svs_st_3;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      gain_sva_2 <= 10'b0000000000;
    end
    else if ( core_wen & reg_gain_adjust_rsc_triosy_obj_iswt0_cse & CHECK_io_read_gain_adjust_rsc_svs_st_1
        ) begin
      gain_sva_2 <= gain_sva_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      CHECK_io_read_gain_adjust_rsc_svs_st_2 <= 1'b0;
      sum_c_tmp_sva_2 <= 25'b0000000000000000000000000;
    end
    else if ( CHECK_and_1_cse ) begin
      CHECK_io_read_gain_adjust_rsc_svs_st_2 <= CHECK_io_read_gain_adjust_rsc_svs_st_1;
      sum_c_tmp_sva_2 <= sum_c_tmp_sva_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      CHECK_io_read_gain_adjust_rsc_svs_st_3 <= 1'b0;
    end
    else if ( core_wen & main_stage_0_3 ) begin
      CHECK_io_read_gain_adjust_rsc_svs_st_3 <= CHECK_io_read_gain_adjust_rsc_svs_st_2;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      gain_sva_1 <= 10'b0000000000;
    end
    else if ( core_wen & gain_adjust_rsci_idat ) begin
      gain_sva_1 <= gain_rsci_idat;
    end
  end
  assign and_3_nl = main_stage_0_5 & (~ CHECK_io_read_gain_adjust_rsc_svs_4);
  assign nl_reg_operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b_cse  = conv_u2u_25_26(product_mul_cmp_z_oreg)
      + conv_u2u_25_26(sum_c_tmp_sva_2);

  function automatic  MUX_s_1_2_2;
    input  input_0;
    input  input_1;
    input  sel;
    reg  result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic [25:0] MUX_v_26_2_2;
    input [25:0] input_0;
    input [25:0] input_1;
    input  sel;
    reg [25:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_26_2_2 = result;
  end
  endfunction


  function automatic [25:0] conv_u2u_25_26 ;
    input [24:0]  vector ;
  begin
    conv_u2u_25_26 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    mult_add_pipeline
// ------------------------------------------------------------------


module mult_add_pipeline (
  clk, rst, a_rsc_dat, a_rsc_vld, a_rsc_rdy, b_rsc_dat, b_rsc_vld, b_rsc_rdy, c_rsc_dat,
      c_rsc_vld, c_rsc_rdy, gain_rsc_dat, gain_rsc_triosy_lz, gain_adjust_rsc_dat,
      gain_adjust_rsc_triosy_lz, result_rsc_dat, result_rsc_vld, result_rsc_rdy
);
  input clk;
  input rst;
  input [10:0] a_rsc_dat;
  input a_rsc_vld;
  output a_rsc_rdy;
  input [13:0] b_rsc_dat;
  input b_rsc_vld;
  output b_rsc_rdy;
  input [24:0] c_rsc_dat;
  input c_rsc_vld;
  output c_rsc_rdy;
  input [9:0] gain_rsc_dat;
  output gain_rsc_triosy_lz;
  input gain_adjust_rsc_dat;
  output gain_adjust_rsc_triosy_lz;
  output [29:0] result_rsc_dat;
  output result_rsc_vld;
  input result_rsc_rdy;


  // Interconnect Declarations
  wire [9:0] operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_a;
  wire [25:0] operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b;
  wire [10:0] product_mul_cmp_a;
  wire [13:0] product_mul_cmp_b;


  // Interconnect Declarations for Component Instantiations 
  wire [33:0] nl_mult_add_pipeline_core_inst_operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z;
  assign nl_mult_add_pipeline_core_inst_operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z
      = conv_u2u_37_34($signed(operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_a)
      * $signed(conv_u2s_26_27(operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b)));
  wire [24:0] nl_mult_add_pipeline_core_inst_product_mul_cmp_z;
  assign nl_mult_add_pipeline_core_inst_product_mul_cmp_z = conv_u2u_25_25(product_mul_cmp_a
      * product_mul_cmp_b);
  mult_add_pipeline_core mult_add_pipeline_core_inst (
      .clk(clk),
      .rst(rst),
      .a_rsc_dat(a_rsc_dat),
      .a_rsc_vld(a_rsc_vld),
      .a_rsc_rdy(a_rsc_rdy),
      .b_rsc_dat(b_rsc_dat),
      .b_rsc_vld(b_rsc_vld),
      .b_rsc_rdy(b_rsc_rdy),
      .c_rsc_dat(c_rsc_dat),
      .c_rsc_vld(c_rsc_vld),
      .c_rsc_rdy(c_rsc_rdy),
      .gain_rsc_dat(gain_rsc_dat),
      .gain_rsc_triosy_lz(gain_rsc_triosy_lz),
      .gain_adjust_rsc_dat(gain_adjust_rsc_dat),
      .gain_adjust_rsc_triosy_lz(gain_adjust_rsc_triosy_lz),
      .result_rsc_dat(result_rsc_dat),
      .result_rsc_vld(result_rsc_vld),
      .result_rsc_rdy(result_rsc_rdy),
      .operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_a(operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_a),
      .operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b(operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_b),
      .operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z(nl_mult_add_pipeline_core_inst_operator_10_2_true_AC_TRN_AC_WRAP_26_false_mul_cmp_z[33:0]),
      .product_mul_cmp_a(product_mul_cmp_a),
      .product_mul_cmp_b(product_mul_cmp_b),
      .product_mul_cmp_z(nl_mult_add_pipeline_core_inst_product_mul_cmp_z[24:0])
    );

  function automatic [26:0] conv_u2s_26_27 ;
    input [25:0]  vector ;
  begin
    conv_u2s_26_27 =  {1'b0, vector};
  end
  endfunction


  function automatic [24:0] conv_u2u_25_25 ;
    input [24:0]  vector ;
  begin
    conv_u2u_25_25 = vector;
  end
  endfunction


  function automatic [33:0] conv_u2u_37_34 ;
    input [36:0]  vector ;
  begin
    conv_u2u_37_34 = vector[33:0];
  end
  endfunction

endmodule



